package mybatis.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class HouseFundPlan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housefund_plan.id
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housefund_plan.tenant_id
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housefund_plan.type
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housefund_plan.name
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housefund_plan.prov_code
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    private String provCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housefund_plan.city_code
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housefund_plan.region_name
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    private String regionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housefund_plan.province_name
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housefund_plan.city_name
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housefund_plan.housefund_basefee
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    private BigDecimal housefundBasefee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housefund_plan.create_time
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housefund_plan.update_time
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housefund_plan.id
     *
     * @return the value of t_housefund_plan.id
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housefund_plan.id
     *
     * @param id the value for t_housefund_plan.id
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housefund_plan.tenant_id
     *
     * @return the value of t_housefund_plan.tenant_id
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housefund_plan.tenant_id
     *
     * @param tenantId the value for t_housefund_plan.tenant_id
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housefund_plan.type
     *
     * @return the value of t_housefund_plan.type
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housefund_plan.type
     *
     * @param type the value for t_housefund_plan.type
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housefund_plan.name
     *
     * @return the value of t_housefund_plan.name
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housefund_plan.name
     *
     * @param name the value for t_housefund_plan.name
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housefund_plan.prov_code
     *
     * @return the value of t_housefund_plan.prov_code
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public String getProvCode() {
        return provCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housefund_plan.prov_code
     *
     * @param provCode the value for t_housefund_plan.prov_code
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public void setProvCode(String provCode) {
        this.provCode = provCode == null ? null : provCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housefund_plan.city_code
     *
     * @return the value of t_housefund_plan.city_code
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housefund_plan.city_code
     *
     * @param cityCode the value for t_housefund_plan.city_code
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housefund_plan.region_name
     *
     * @return the value of t_housefund_plan.region_name
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housefund_plan.region_name
     *
     * @param regionName the value for t_housefund_plan.region_name
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housefund_plan.province_name
     *
     * @return the value of t_housefund_plan.province_name
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housefund_plan.province_name
     *
     * @param provinceName the value for t_housefund_plan.province_name
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housefund_plan.city_name
     *
     * @return the value of t_housefund_plan.city_name
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housefund_plan.city_name
     *
     * @param cityName the value for t_housefund_plan.city_name
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housefund_plan.housefund_basefee
     *
     * @return the value of t_housefund_plan.housefund_basefee
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public BigDecimal getHousefundBasefee() {
        return housefundBasefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housefund_plan.housefund_basefee
     *
     * @param housefundBasefee the value for t_housefund_plan.housefund_basefee
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public void setHousefundBasefee(BigDecimal housefundBasefee) {
        this.housefundBasefee = housefundBasefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housefund_plan.create_time
     *
     * @return the value of t_housefund_plan.create_time
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housefund_plan.create_time
     *
     * @param createTime the value for t_housefund_plan.create_time
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housefund_plan.update_time
     *
     * @return the value of t_housefund_plan.update_time
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housefund_plan.update_time
     *
     * @param updateTime the value for t_housefund_plan.update_time
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}