/**
 * This class is generated by jOOQ
 */
package jooq.model.tables;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 存储津贴方案 | 王默 | 2016-09-14 | 津贴设置页面，用户界面操作
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAllowancePlan extends org.jooq.impl.TableImpl<jooq.model.tables.records.TAllowancePlanRecord> {

	private static final long serialVersionUID = 1944446039;

	/**
	 * The singleton instance of <code>oa_salary.t_allowance_plan</code>
	 */
	public static final jooq.model.tables.TAllowancePlan T_ALLOWANCE_PLAN = new jooq.model.tables.TAllowancePlan();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<jooq.model.tables.records.TAllowancePlanRecord> getRecordType() {
		return jooq.model.tables.records.TAllowancePlanRecord.class;
	}

	/**
	 * The column <code>oa_salary.t_allowance_plan.id</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAllowancePlanRecord, org.jooq.types.UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_allowance_plan.tenant_id</code>. 公司ID | 王默 | 2016-09-14 | 账号模块
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAllowancePlanRecord, java.lang.Long> TENANT_ID = createField("tenant_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "公司ID | 王默 | 2016-09-14 | 账号模块");

	/**
	 * The column <code>oa_salary.t_allowance_plan.allowance_name</code>. 津贴名称 | 王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAllowancePlanRecord, java.lang.String> ALLOWANCE_NAME = createField("allowance_name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "津贴名称 | 王默 | 2016-09-14 | 用户界面操作，输入");

	/**
	 * The column <code>oa_salary.t_allowance_plan.allowance_pay_type</code>. 津贴发放方式（比如，出勤一天多少钱） | 王默 | 2016-09-14 | @1: @2: @3: | 前台用户操作，选择
ps:有几种，还未确定
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAllowancePlanRecord, org.jooq.types.UByte> ALLOWANCE_PAY_TYPE = createField("allowance_pay_type", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false).defaulted(true), this, "津贴发放方式（比如，出勤一天多少钱） | 王默 | 2016-09-14 | @1: @2: @3: | 前台用户操作，选择\nps:有几种，还未确定");

	/**
	 * The column <code>oa_salary.t_allowance_plan.how_much</code>. 对应津贴发放方式的金额 | 王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAllowancePlanRecord, java.lang.Integer> HOW_MUCH = createField("how_much", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "对应津贴发放方式的金额 | 王默 | 2016-09-14 | 用户界面操作，输入");

	/**
	 * The column <code>oa_salary.t_allowance_plan.is_critical_attendance_day_enabled</code>. 是否根据出勤天数判断是否有该项津贴 | 王默 | 2016-09-14 | @0:disable(default) @1:enabled | 用户界面操作，switch按钮
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAllowancePlanRecord, org.jooq.types.UByte> IS_CRITICAL_ATTENDANCE_DAY_ENABLED = createField("is_critical_attendance_day_enabled", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false).defaulted(true), this, "是否根据出勤天数判断是否有该项津贴 | 王默 | 2016-09-14 | @0:disable(default) @1:enabled | 用户界面操作，switch按钮");

	/**
	 * The column <code>oa_salary.t_allowance_plan.critical_attendance_day</code>. 根据该出勤天数判断是否有该项津贴 | 王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAllowancePlanRecord, org.jooq.types.UByte> CRITICAL_ATTENDANCE_DAY = createField("critical_attendance_day", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false).defaulted(true), this, "根据该出勤天数判断是否有该项津贴 | 王默 | 2016-09-14 | 用户界面操作，输入");

	/**
	 * The column <code>oa_salary.t_allowance_plan.adapted_account_type</code>. 津贴适用的账号类型 | 王默 | 2016-09-14 | @1:正式 @2:劳务 | 用户界面操作，复选框
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAllowancePlanRecord, org.jooq.types.UByte> ADAPTED_ACCOUNT_TYPE = createField("adapted_account_type", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false).defaulted(true), this, "津贴适用的账号类型 | 王默 | 2016-09-14 | @1:正式 @2:劳务 | 用户界面操作，复选框");

	/**
	 * The column <code>oa_salary.t_allowance_plan.allowance_description</code>. 津贴描述 | 王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAllowancePlanRecord, java.lang.String> ALLOWANCE_DESCRIPTION = createField("allowance_description", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false).defaulted(true), this, "津贴描述 | 王默 | 2016-09-14 | 用户界面操作，输入");

	/**
	 * The column <code>oa_salary.t_allowance_plan.create_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAllowancePlanRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>oa_salary.t_allowance_plan.update_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAllowancePlanRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>oa_salary.t_allowance_plan</code> table reference
	 */
	public TAllowancePlan() {
		this("t_allowance_plan", null);
	}

	/**
	 * Create an aliased <code>oa_salary.t_allowance_plan</code> table reference
	 */
	public TAllowancePlan(java.lang.String alias) {
		this(alias, jooq.model.tables.TAllowancePlan.T_ALLOWANCE_PLAN);
	}

	private TAllowancePlan(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TAllowancePlanRecord> aliased) {
		this(alias, aliased, null);
	}

	private TAllowancePlan(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TAllowancePlanRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, jooq.model.OaSalary.OA_SALARY, aliased, parameters, "薪酬模块 | 存储津贴方案 | 王默 | 2016-09-14 | 津贴设置页面，用户界面操作");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<jooq.model.tables.records.TAllowancePlanRecord, org.jooq.types.UInteger> getIdentity() {
		return jooq.model.Keys.IDENTITY_T_ALLOWANCE_PLAN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<jooq.model.tables.records.TAllowancePlanRecord> getPrimaryKey() {
		return jooq.model.Keys.KEY_T_ALLOWANCE_PLAN_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<jooq.model.tables.records.TAllowancePlanRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<jooq.model.tables.records.TAllowancePlanRecord>>asList(jooq.model.Keys.KEY_T_ALLOWANCE_PLAN_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public jooq.model.tables.TAllowancePlan as(java.lang.String alias) {
		return new jooq.model.tables.TAllowancePlan(alias, this);
	}

	/**
	 * Rename this table
	 */
	public jooq.model.tables.TAllowancePlan rename(java.lang.String name) {
		return new jooq.model.tables.TAllowancePlan(name, null);
	}
}
