/**
 * This class is generated by jOOQ
 */
package jooq.model.tables;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 存储上传的考勤数据 | 邓刚&王默 | 2016-09-14 | excel上传
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAttendanceData extends org.jooq.impl.TableImpl<jooq.model.tables.records.TAttendanceDataRecord> {

	private static final long serialVersionUID = -365736004;

	/**
	 * The singleton instance of <code>oa_salary.t_attendance_data</code>
	 */
	public static final jooq.model.tables.TAttendanceData T_ATTENDANCE_DATA = new jooq.model.tables.TAttendanceData();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<jooq.model.tables.records.TAttendanceDataRecord> getRecordType() {
		return jooq.model.tables.records.TAttendanceDataRecord.class;
	}

	/**
	 * The column <code>oa_salary.t_attendance_data.id</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAttendanceDataRecord, org.jooq.types.ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_attendance_data.tenant_id</code>. 公司ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAttendanceDataRecord, java.lang.Long> TENANT_ID = createField("tenant_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "公司ID | 邓刚&王默 | 2016-09-14 | 账号模块");

	/**
	 * The column <code>oa_salary.t_attendance_data.user_id</code>. 用户ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAttendanceDataRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "用户ID | 邓刚&王默 | 2016-09-14 | 账号模块");

	/**
	 * The column <code>oa_salary.t_attendance_data.attendance_days</code>. 实际出勤天数 | 邓刚&王默 | 2016-09-14 | excel上传
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAttendanceDataRecord, java.lang.Double> ATTENDANCE_DAYS = createField("attendance_days", org.jooq.impl.SQLDataType.DOUBLE.nullable(false).defaulted(true), this, "实际出勤天数 | 邓刚&王默 | 2016-09-14 | excel上传");

	/**
	 * The column <code>oa_salary.t_attendance_data.absenteeism_days</code>. 旷工天数 | 邓刚&王默 | 2016-09-14 | excel上传
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAttendanceDataRecord, java.lang.Double> ABSENTEEISM_DAYS = createField("absenteeism_days", org.jooq.impl.SQLDataType.DOUBLE.nullable(false).defaulted(true), this, "旷工天数 | 邓刚&王默 | 2016-09-14 | excel上传");

	/**
	 * The column <code>oa_salary.t_attendance_data.annual_leave_days</code>. 年假天数 | 邓刚&王默 | 2016-09-14 | excel上传
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAttendanceDataRecord, java.lang.Double> ANNUAL_LEAVE_DAYS = createField("annual_leave_days", org.jooq.impl.SQLDataType.DOUBLE.nullable(false).defaulted(true), this, "年假天数 | 邓刚&王默 | 2016-09-14 | excel上传");

	/**
	 * The column <code>oa_salary.t_attendance_data.sick_leave_days</code>. 病假天数 | 邓刚&王默 | 2016-09-14 | excel上传
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAttendanceDataRecord, java.lang.Double> SICK_LEAVE_DAYS = createField("sick_leave_days", org.jooq.impl.SQLDataType.DOUBLE.nullable(false).defaulted(true), this, "病假天数 | 邓刚&王默 | 2016-09-14 | excel上传");

	/**
	 * The column <code>oa_salary.t_attendance_data.off_leave_days</code>. 调休天数 | 邓刚&王默 | 2016-09-14 | excel上传
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAttendanceDataRecord, java.lang.Double> OFF_LEAVE_DAYS = createField("off_leave_days", org.jooq.impl.SQLDataType.DOUBLE.nullable(false).defaulted(true), this, "调休天数 | 邓刚&王默 | 2016-09-14 | excel上传");

	/**
	 * The column <code>oa_salary.t_attendance_data.affair_leave_days</code>. 事假天数 | 邓刚&王默 | 2016-09-14 | excel上传
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAttendanceDataRecord, java.lang.Double> AFFAIR_LEAVE_DAYS = createField("affair_leave_days", org.jooq.impl.SQLDataType.DOUBLE.nullable(false).defaulted(true), this, "事假天数 | 邓刚&王默 | 2016-09-14 | excel上传");

	/**
	 * The column <code>oa_salary.t_attendance_data.funeral_leave_days</code>. 丧假天数 | 邓刚&王默 | 2016-09-14 | excel上传
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAttendanceDataRecord, java.lang.Double> FUNERAL_LEAVE_DAYS = createField("funeral_leave_days", org.jooq.impl.SQLDataType.DOUBLE.nullable(false).defaulted(true), this, "丧假天数 | 邓刚&王默 | 2016-09-14 | excel上传");

	/**
	 * The column <code>oa_salary.t_attendance_data.marriage_leave_days</code>. 婚假天数 | 邓刚&王默 | 2016-09-14 | excel上传
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAttendanceDataRecord, java.lang.Double> MARRIAGE_LEAVE_DAYS = createField("marriage_leave_days", org.jooq.impl.SQLDataType.DOUBLE.nullable(false).defaulted(true), this, "婚假天数 | 邓刚&王默 | 2016-09-14 | excel上传");

	/**
	 * The column <code>oa_salary.t_attendance_data.maternity_leave_days</code>. 产假天数 | 邓刚&王默 | 2016-09-14 | excel上传
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAttendanceDataRecord, java.lang.Double> MATERNITY_LEAVE_DAYS = createField("maternity_leave_days", org.jooq.impl.SQLDataType.DOUBLE.nullable(false).defaulted(true), this, "产假天数 | 邓刚&王默 | 2016-09-14 | excel上传");

	/**
	 * The column <code>oa_salary.t_attendance_data.paternity_leave_days</code>. 陪产假天数 | 邓刚&王默 | 2016-09-14 | excel上传
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAttendanceDataRecord, java.lang.Double> PATERNITY_LEAVE_DAYS = createField("paternity_leave_days", org.jooq.impl.SQLDataType.DOUBLE.nullable(false).defaulted(true), this, "陪产假天数 | 邓刚&王默 | 2016-09-14 | excel上传");

	/**
	 * The column <code>oa_salary.t_attendance_data.create_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAttendanceDataRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>oa_salary.t_attendance_data.update_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TAttendanceDataRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>oa_salary.t_attendance_data</code> table reference
	 */
	public TAttendanceData() {
		this("t_attendance_data", null);
	}

	/**
	 * Create an aliased <code>oa_salary.t_attendance_data</code> table reference
	 */
	public TAttendanceData(java.lang.String alias) {
		this(alias, jooq.model.tables.TAttendanceData.T_ATTENDANCE_DATA);
	}

	private TAttendanceData(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TAttendanceDataRecord> aliased) {
		this(alias, aliased, null);
	}

	private TAttendanceData(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TAttendanceDataRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, jooq.model.OaSalary.OA_SALARY, aliased, parameters, "薪酬模块 | 存储上传的考勤数据 | 邓刚&王默 | 2016-09-14 | excel上传");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<jooq.model.tables.records.TAttendanceDataRecord, org.jooq.types.ULong> getIdentity() {
		return jooq.model.Keys.IDENTITY_T_ATTENDANCE_DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<jooq.model.tables.records.TAttendanceDataRecord> getPrimaryKey() {
		return jooq.model.Keys.KEY_T_ATTENDANCE_DATA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<jooq.model.tables.records.TAttendanceDataRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<jooq.model.tables.records.TAttendanceDataRecord>>asList(jooq.model.Keys.KEY_T_ATTENDANCE_DATA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public jooq.model.tables.TAttendanceData as(java.lang.String alias) {
		return new jooq.model.tables.TAttendanceData(alias, this);
	}

	/**
	 * Rename this table
	 */
	public jooq.model.tables.TAttendanceData rename(java.lang.String name) {
		return new jooq.model.tables.TAttendanceData(name, null);
	}
}
