/**
 * This class is generated by jOOQ
 */
package jooq.model.tables;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 基础工资表，包括调薪历史 | 王默 | 2016-09-14 | 调薪页面，用户界面操作，输入
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBasicSalary extends org.jooq.impl.TableImpl<jooq.model.tables.records.TBasicSalaryRecord> {

	private static final long serialVersionUID = -1908579961;

	/**
	 * The singleton instance of <code>oa_salary.t_basic_salary</code>
	 */
	public static final jooq.model.tables.TBasicSalary T_BASIC_SALARY = new jooq.model.tables.TBasicSalary();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<jooq.model.tables.records.TBasicSalaryRecord> getRecordType() {
		return jooq.model.tables.records.TBasicSalaryRecord.class;
	}

	/**
	 * The column <code>oa_salary.t_basic_salary.id</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TBasicSalaryRecord, org.jooq.types.ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_basic_salary.tenant_id</code>. 公司ID | 王默 | 2016-09-14 | 账号模块
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TBasicSalaryRecord, java.lang.Long> TENANT_ID = createField("tenant_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "公司ID | 王默 | 2016-09-14 | 账号模块");

	/**
	 * The column <code>oa_salary.t_basic_salary.user_id</code>. 用户ID | 王默 | 2016-09-14 | 账号模块
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TBasicSalaryRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "用户ID | 王默 | 2016-09-14 | 账号模块");

	/**
	 * The column <code>oa_salary.t_basic_salary.basic_salary_adjustment_id</code>. 调薪记录ID | 王默 | 2016-09-13 | t_basic_salary_adjustment.id
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TBasicSalaryRecord, org.jooq.types.ULong> BASIC_SALARY_ADJUSTMENT_ID = createField("basic_salary_adjustment_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "调薪记录ID | 王默 | 2016-09-13 | t_basic_salary_adjustment.id");

	/**
	 * The column <code>oa_salary.t_basic_salary.basic_salary_type_id</code>. 对应基本工资项的ID | 王默 | 2016-09-13 | t_basic_salary_type.id
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TBasicSalaryRecord, org.jooq.types.ULong> BASIC_SALARY_TYPE_ID = createField("basic_salary_type_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "对应基本工资项的ID | 王默 | 2016-09-13 | t_basic_salary_type.id");

	/**
	 * The column <code>oa_salary.t_basic_salary.how_much</code>. 该基础工资项的金额 | 王默 | 2016-09-13 | 用户界面操作，输入
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TBasicSalaryRecord, java.lang.Integer> HOW_MUCH = createField("how_much", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "该基础工资项的金额 | 王默 | 2016-09-13 | 用户界面操作，输入");

	/**
	 * The column <code>oa_salary.t_basic_salary.create_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TBasicSalaryRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>oa_salary.t_basic_salary.update_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TBasicSalaryRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>oa_salary.t_basic_salary</code> table reference
	 */
	public TBasicSalary() {
		this("t_basic_salary", null);
	}

	/**
	 * Create an aliased <code>oa_salary.t_basic_salary</code> table reference
	 */
	public TBasicSalary(java.lang.String alias) {
		this(alias, jooq.model.tables.TBasicSalary.T_BASIC_SALARY);
	}

	private TBasicSalary(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TBasicSalaryRecord> aliased) {
		this(alias, aliased, null);
	}

	private TBasicSalary(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TBasicSalaryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, jooq.model.OaSalary.OA_SALARY, aliased, parameters, "薪酬模块 | 基础工资表，包括调薪历史 | 王默 | 2016-09-14 | 调薪页面，用户界面操作，输入");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<jooq.model.tables.records.TBasicSalaryRecord, org.jooq.types.ULong> getIdentity() {
		return jooq.model.Keys.IDENTITY_T_BASIC_SALARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<jooq.model.tables.records.TBasicSalaryRecord> getPrimaryKey() {
		return jooq.model.Keys.KEY_T_BASIC_SALARY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<jooq.model.tables.records.TBasicSalaryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<jooq.model.tables.records.TBasicSalaryRecord>>asList(jooq.model.Keys.KEY_T_BASIC_SALARY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public jooq.model.tables.TBasicSalary as(java.lang.String alias) {
		return new jooq.model.tables.TBasicSalary(alias, this);
	}

	/**
	 * Rename this table
	 */
	public jooq.model.tables.TBasicSalary rename(java.lang.String name) {
		return new jooq.model.tables.TBasicSalary(name, null);
	}
}
