/**
 * This class is generated by jOOQ
 */
package jooq.model.tables;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 存储各公司自定义的奖金类型 | 邓刚&王默 | 2016-09-14 | 奖金设置页面，用户界面操作
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBonusType extends org.jooq.impl.TableImpl<jooq.model.tables.records.TBonusTypeRecord> {

	private static final long serialVersionUID = -1721860896;

	/**
	 * The singleton instance of <code>oa_salary.t_bonus_type</code>
	 */
	public static final jooq.model.tables.TBonusType T_BONUS_TYPE = new jooq.model.tables.TBonusType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<jooq.model.tables.records.TBonusTypeRecord> getRecordType() {
		return jooq.model.tables.records.TBonusTypeRecord.class;
	}

	/**
	 * The column <code>oa_salary.t_bonus_type.id</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TBonusTypeRecord, org.jooq.types.UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_bonus_type.tenant_id</code>. 公司ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TBonusTypeRecord, java.lang.Long> TENANT_ID = createField("tenant_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "公司ID | 邓刚&王默 | 2016-09-14 | 账号模块");

	/**
	 * The column <code>oa_salary.t_bonus_type.bonus_name</code>. 奖金名称 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TBonusTypeRecord, java.lang.String> BONUS_NAME = createField("bonus_name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "奖金名称 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入");

	/**
	 * The column <code>oa_salary.t_bonus_type.cycle</code>. 奖金发放周期 | 邓刚&王默 | 2016-09-14 | @1:月 @2:季度 @3:年 @4:非周期性发放 | 用户界面操作，select
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TBonusTypeRecord, org.jooq.types.UByte> CYCLE = createField("cycle", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false).defaulted(true), this, "奖金发放周期 | 邓刚&王默 | 2016-09-14 | @1:月 @2:季度 @3:年 @4:非周期性发放 | 用户界面操作，select");

	/**
	 * The column <code>oa_salary.t_bonus_type.create_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TBonusTypeRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>oa_salary.t_bonus_type.update_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TBonusTypeRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>oa_salary.t_bonus_type</code> table reference
	 */
	public TBonusType() {
		this("t_bonus_type", null);
	}

	/**
	 * Create an aliased <code>oa_salary.t_bonus_type</code> table reference
	 */
	public TBonusType(java.lang.String alias) {
		this(alias, jooq.model.tables.TBonusType.T_BONUS_TYPE);
	}

	private TBonusType(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TBonusTypeRecord> aliased) {
		this(alias, aliased, null);
	}

	private TBonusType(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TBonusTypeRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, jooq.model.OaSalary.OA_SALARY, aliased, parameters, "薪酬模块 | 存储各公司自定义的奖金类型 | 邓刚&王默 | 2016-09-14 | 奖金设置页面，用户界面操作");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<jooq.model.tables.records.TBonusTypeRecord, org.jooq.types.UInteger> getIdentity() {
		return jooq.model.Keys.IDENTITY_T_BONUS_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<jooq.model.tables.records.TBonusTypeRecord> getPrimaryKey() {
		return jooq.model.Keys.KEY_T_BONUS_TYPE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<jooq.model.tables.records.TBonusTypeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<jooq.model.tables.records.TBonusTypeRecord>>asList(jooq.model.Keys.KEY_T_BONUS_TYPE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public jooq.model.tables.TBonusType as(java.lang.String alias) {
		return new jooq.model.tables.TBonusType(alias, this);
	}

	/**
	 * Rename this table
	 */
	public jooq.model.tables.TBonusType rename(java.lang.String name) {
		return new jooq.model.tables.TBonusType(name, null);
	}
}
