/**
 * This class is generated by jOOQ
 */
package jooq.model.tables;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 存储归档历史 | 王默 | 2016-09-14 | 历史归档页面，用户界面操作
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TFilingHistory extends org.jooq.impl.TableImpl<jooq.model.tables.records.TFilingHistoryRecord> {

	private static final long serialVersionUID = 1284652616;

	/**
	 * The singleton instance of <code>oa_salary.t_filing_history</code>
	 */
	public static final jooq.model.tables.TFilingHistory T_FILING_HISTORY = new jooq.model.tables.TFilingHistory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<jooq.model.tables.records.TFilingHistoryRecord> getRecordType() {
		return jooq.model.tables.records.TFilingHistoryRecord.class;
	}

	/**
	 * The column <code>oa_salary.t_filing_history.id</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TFilingHistoryRecord, org.jooq.types.ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_filing_history.tenant_id</code>. 公司ID | 王默 | 2016-09-14 | 账号模块
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TFilingHistoryRecord, java.lang.Long> TENANT_ID = createField("tenant_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "公司ID | 王默 | 2016-09-14 | 账号模块");

	/**
	 * The column <code>oa_salary.t_filing_history.filing_time</code>. 归档的月份 | 王默 | 2016-09-14 | 用户界面操作
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TFilingHistoryRecord, java.lang.Integer> FILING_TIME = createField("filing_time", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "归档的月份 | 王默 | 2016-09-14 | 用户界面操作");

	/**
	 * The column <code>oa_salary.t_filing_history.filing_state</code>. 归档状态 | 王默 | 2016-09-14 | @0:未归档 @1:已归档 @2:已封帐 | 归档行为
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TFilingHistoryRecord, org.jooq.types.UByte> FILING_STATE = createField("filing_state", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false).defaulted(true), this, "归档状态 | 王默 | 2016-09-14 | @0:未归档 @1:已归档 @2:已封帐 | 归档行为");

	/**
	 * The column <code>oa_salary.t_filing_history.create_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TFilingHistoryRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>oa_salary.t_filing_history.update_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TFilingHistoryRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>oa_salary.t_filing_history</code> table reference
	 */
	public TFilingHistory() {
		this("t_filing_history", null);
	}

	/**
	 * Create an aliased <code>oa_salary.t_filing_history</code> table reference
	 */
	public TFilingHistory(java.lang.String alias) {
		this(alias, jooq.model.tables.TFilingHistory.T_FILING_HISTORY);
	}

	private TFilingHistory(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TFilingHistoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private TFilingHistory(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TFilingHistoryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, jooq.model.OaSalary.OA_SALARY, aliased, parameters, "薪酬模块 | 存储归档历史 | 王默 | 2016-09-14 | 历史归档页面，用户界面操作");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<jooq.model.tables.records.TFilingHistoryRecord, org.jooq.types.ULong> getIdentity() {
		return jooq.model.Keys.IDENTITY_T_FILING_HISTORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<jooq.model.tables.records.TFilingHistoryRecord> getPrimaryKey() {
		return jooq.model.Keys.KEY_T_FILING_HISTORY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<jooq.model.tables.records.TFilingHistoryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<jooq.model.tables.records.TFilingHistoryRecord>>asList(jooq.model.Keys.KEY_T_FILING_HISTORY_PRIMARY, jooq.model.Keys.KEY_T_FILING_HISTORY_UIND_TENANT_DATE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public jooq.model.tables.TFilingHistory as(java.lang.String alias) {
		return new jooq.model.tables.TFilingHistory(alias, this);
	}

	/**
	 * Rename this table
	 */
	public jooq.model.tables.TFilingHistory rename(java.lang.String name) {
		return new jooq.model.tables.TFilingHistory(name, null);
	}
}
