/**
 * This class is generated by jOOQ
 */
package jooq.model.tables;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 公积金方案 | 邓刚&王默 | 2016-10-11 | 公积金方案配置页
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class THousefundPlan extends org.jooq.impl.TableImpl<jooq.model.tables.records.THousefundPlanRecord> {

	private static final long serialVersionUID = -1746874643;

	/**
	 * The singleton instance of <code>oa_salary.t_housefund_plan</code>
	 */
	public static final jooq.model.tables.THousefundPlan T_HOUSEFUND_PLAN = new jooq.model.tables.THousefundPlan();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<jooq.model.tables.records.THousefundPlanRecord> getRecordType() {
		return jooq.model.tables.records.THousefundPlanRecord.class;
	}

	/**
	 * The column <code>oa_salary.t_housefund_plan.id</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.THousefundPlanRecord, org.jooq.types.ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_housefund_plan.tenant_id</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.THousefundPlanRecord, org.jooq.types.ULong> TENANT_ID = createField("tenant_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_housefund_plan.name</code>. 社保方案的名字 | 邓刚&王默 | 2016-10-11 | 用户界面操作-输入
	 */
	public final org.jooq.TableField<jooq.model.tables.records.THousefundPlanRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "社保方案的名字 | 邓刚&王默 | 2016-10-11 | 用户界面操作-输入");

	/**
	 * The column <code>oa_salary.t_housefund_plan.prov_code</code>. 方案对应地区在redis中的key | 邓刚&王默 | 2016-10-11 | 生成
	 */
	public final org.jooq.TableField<jooq.model.tables.records.THousefundPlanRecord, java.lang.String> PROV_CODE = createField("prov_code", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "方案对应地区在redis中的key | 邓刚&王默 | 2016-10-11 | 生成");

	/**
	 * The column <code>oa_salary.t_housefund_plan.city_code</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.THousefundPlanRecord, java.lang.String> CITY_CODE = createField("city_code", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_housefund_plan.region_name</code>. 区域名字  | 邓刚&王默 | 2016-09-14 | 
	 */
	public final org.jooq.TableField<jooq.model.tables.records.THousefundPlanRecord, java.lang.String> REGION_NAME = createField("region_name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "区域名字  | 邓刚&王默 | 2016-09-14 | ");

	/**
	 * The column <code>oa_salary.t_housefund_plan.province_name</code>. 省份名字 | 邓刚&王默 | 2016-09-14 | 
	 */
	public final org.jooq.TableField<jooq.model.tables.records.THousefundPlanRecord, java.lang.String> PROVINCE_NAME = createField("province_name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "省份名字 | 邓刚&王默 | 2016-09-14 | ");

	/**
	 * The column <code>oa_salary.t_housefund_plan.city_name</code>. 城市名字 | 邓刚&王默 | 2016-09-14 | 
	 */
	public final org.jooq.TableField<jooq.model.tables.records.THousefundPlanRecord, java.lang.String> CITY_NAME = createField("city_name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "城市名字 | 邓刚&王默 | 2016-09-14 | ");

	/**
	 * The column <code>oa_salary.t_housefund_plan.housefund_basefee</code>. 该方案对应的公积金基数 | 邓刚&王默 | 2016-10-11 | 用户界面操作-输入
	 */
	public final org.jooq.TableField<jooq.model.tables.records.THousefundPlanRecord, java.lang.Long> HOUSEFUND_BASEFEE = createField("housefund_basefee", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "该方案对应的公积金基数 | 邓刚&王默 | 2016-10-11 | 用户界面操作-输入");

	/**
	 * The column <code>oa_salary.t_housefund_plan.create_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.THousefundPlanRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>oa_salary.t_housefund_plan.update_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.THousefundPlanRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>oa_salary.t_housefund_plan</code> table reference
	 */
	public THousefundPlan() {
		this("t_housefund_plan", null);
	}

	/**
	 * Create an aliased <code>oa_salary.t_housefund_plan</code> table reference
	 */
	public THousefundPlan(java.lang.String alias) {
		this(alias, jooq.model.tables.THousefundPlan.T_HOUSEFUND_PLAN);
	}

	private THousefundPlan(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.THousefundPlanRecord> aliased) {
		this(alias, aliased, null);
	}

	private THousefundPlan(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.THousefundPlanRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, jooq.model.OaSalary.OA_SALARY, aliased, parameters, "薪酬模块 | 公积金方案 | 邓刚&王默 | 2016-10-11 | 公积金方案配置页");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<jooq.model.tables.records.THousefundPlanRecord, org.jooq.types.ULong> getIdentity() {
		return jooq.model.Keys.IDENTITY_T_HOUSEFUND_PLAN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<jooq.model.tables.records.THousefundPlanRecord> getPrimaryKey() {
		return jooq.model.Keys.KEY_T_HOUSEFUND_PLAN_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<jooq.model.tables.records.THousefundPlanRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<jooq.model.tables.records.THousefundPlanRecord>>asList(jooq.model.Keys.KEY_T_HOUSEFUND_PLAN_PRIMARY, jooq.model.Keys.KEY_T_HOUSEFUND_PLAN_UINX_LOCATION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public jooq.model.tables.THousefundPlan as(java.lang.String alias) {
		return new jooq.model.tables.THousefundPlan(alias, this);
	}

	/**
	 * Rename this table
	 */
	public jooq.model.tables.THousefundPlan rename(java.lang.String name) {
		return new jooq.model.tables.THousefundPlan(name, null);
	}
}
