/**
 * This class is generated by jOOQ
 */
package jooq.model.tables;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 存储归档历史 | 邓刚&王默 | 2016-09-14 | 历史归档页面，用户界面操作
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TInsuranceFilingHistory extends org.jooq.impl.TableImpl<jooq.model.tables.records.TInsuranceFilingHistoryRecord> {

	private static final long serialVersionUID = -247209763;

	/**
	 * The singleton instance of <code>oa_salary.t_insurance_filing_history</code>
	 */
	public static final jooq.model.tables.TInsuranceFilingHistory T_INSURANCE_FILING_HISTORY = new jooq.model.tables.TInsuranceFilingHistory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<jooq.model.tables.records.TInsuranceFilingHistoryRecord> getRecordType() {
		return jooq.model.tables.records.TInsuranceFilingHistoryRecord.class;
	}

	/**
	 * The column <code>oa_salary.t_insurance_filing_history.tenant_id</code>. 公司ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsuranceFilingHistoryRecord, org.jooq.types.ULong> TENANT_ID = createField("tenant_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false).defaulted(true), this, "公司ID | 邓刚&王默 | 2016-09-14 | 账号模块");

	/**
	 * The column <code>oa_salary.t_insurance_filing_history.current</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsuranceFilingHistoryRecord, java.lang.Integer> CURRENT = createField("current", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_insurance_filing_history.filing_state</code>. 归档状态 | 邓刚&王默 | 2016-09-14 | @0:未归档 @1:社保已归档 @2公积金已归档 @3:已封帐 | 归档行为
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsuranceFilingHistoryRecord, org.jooq.types.UByte> FILING_STATE = createField("filing_state", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false).defaulted(true), this, "归档状态 | 邓刚&王默 | 2016-09-14 | @0:未归档 @1:社保已归档 @2公积金已归档 @3:已封帐 | 归档行为");

	/**
	 * The column <code>oa_salary.t_insurance_filing_history.create_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsuranceFilingHistoryRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>oa_salary.t_insurance_filing_history.update_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsuranceFilingHistoryRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>oa_salary.t_insurance_filing_history</code> table reference
	 */
	public TInsuranceFilingHistory() {
		this("t_insurance_filing_history", null);
	}

	/**
	 * Create an aliased <code>oa_salary.t_insurance_filing_history</code> table reference
	 */
	public TInsuranceFilingHistory(java.lang.String alias) {
		this(alias, jooq.model.tables.TInsuranceFilingHistory.T_INSURANCE_FILING_HISTORY);
	}

	private TInsuranceFilingHistory(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TInsuranceFilingHistoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private TInsuranceFilingHistory(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TInsuranceFilingHistoryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, jooq.model.OaSalary.OA_SALARY, aliased, parameters, "薪酬模块 | 存储归档历史 | 邓刚&王默 | 2016-09-14 | 历史归档页面，用户界面操作");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<jooq.model.tables.records.TInsuranceFilingHistoryRecord> getPrimaryKey() {
		return jooq.model.Keys.KEY_T_INSURANCE_FILING_HISTORY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<jooq.model.tables.records.TInsuranceFilingHistoryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<jooq.model.tables.records.TInsuranceFilingHistoryRecord>>asList(jooq.model.Keys.KEY_T_INSURANCE_FILING_HISTORY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public jooq.model.tables.TInsuranceFilingHistory as(java.lang.String alias) {
		return new jooq.model.tables.TInsuranceFilingHistory(alias, this);
	}

	/**
	 * Rename this table
	 */
	public jooq.model.tables.TInsuranceFilingHistory rename(java.lang.String name) {
		return new jooq.model.tables.TInsuranceFilingHistory(name, null);
	}
}
