/**
 * This class is generated by jOOQ
 */
package jooq.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TInsuranceChangeRecord extends org.jooq.impl.TableImpl<jooq.model.tables.records.TInsuranceChangeRecordRecord> {

	private static final long serialVersionUID = 1680516337;

	/**
	 * The singleton instance of <code>oa_salary.t_insurance_change_record</code>
	 */
	public static final jooq.model.tables.TInsuranceChangeRecord T_INSURANCE_CHANGE_RECORD = new jooq.model.tables.TInsuranceChangeRecord();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<jooq.model.tables.records.TInsuranceChangeRecordRecord> getRecordType() {
		return jooq.model.tables.records.TInsuranceChangeRecordRecord.class;
	}

	/**
	 * The column <code>oa_salary.t_insurance_change_record.id</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsuranceChangeRecordRecord, org.jooq.types.ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_insurance_change_record.tenant_id</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsuranceChangeRecordRecord, java.lang.Long> TENANT_ID = createField("tenant_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_insurance_change_record.user_id</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsuranceChangeRecordRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_insurance_change_record.describ</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsuranceChangeRecordRecord, java.lang.String> DESCRIB = createField("describ", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>oa_salary.t_insurance_change_record.create_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsuranceChangeRecordRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>oa_salary.t_insurance_change_record</code> table reference
	 */
	public TInsuranceChangeRecord() {
		this("t_insurance_change_record", null);
	}

	/**
	 * Create an aliased <code>oa_salary.t_insurance_change_record</code> table reference
	 */
	public TInsuranceChangeRecord(java.lang.String alias) {
		this(alias, jooq.model.tables.TInsuranceChangeRecord.T_INSURANCE_CHANGE_RECORD);
	}

	private TInsuranceChangeRecord(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TInsuranceChangeRecordRecord> aliased) {
		this(alias, aliased, null);
	}

	private TInsuranceChangeRecord(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TInsuranceChangeRecordRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, jooq.model.OaSalary.OA_SALARY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<jooq.model.tables.records.TInsuranceChangeRecordRecord, org.jooq.types.ULong> getIdentity() {
		return jooq.model.Keys.IDENTITY_T_INSURANCE_CHANGE_RECORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<jooq.model.tables.records.TInsuranceChangeRecordRecord> getPrimaryKey() {
		return jooq.model.Keys.KEY_T_INSURANCE_CHANGE_RECORD_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<jooq.model.tables.records.TInsuranceChangeRecordRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<jooq.model.tables.records.TInsuranceChangeRecordRecord>>asList(jooq.model.Keys.KEY_T_INSURANCE_CHANGE_RECORD_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public jooq.model.tables.TInsuranceChangeRecord as(java.lang.String alias) {
		return new jooq.model.tables.TInsuranceChangeRecord(alias, this);
	}

	/**
	 * Rename this table
	 */
	public jooq.model.tables.TInsuranceChangeRecord rename(java.lang.String name) {
		return new jooq.model.tables.TInsuranceChangeRecord(name, null);
	}
}
