/**
 * This class is generated by jOOQ
 */
package jooq.model.tables;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 社保公积金数据表，只记录归档数据 | 王默 | 2016-09-14 | 社保详情页面，和历史归档页面，根据社保公积金配置合成
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TInsurancesHousefundFiling extends org.jooq.impl.TableImpl<jooq.model.tables.records.TInsurancesHousefundFilingRecord> {

	private static final long serialVersionUID = -929649839;

	/**
	 * The singleton instance of <code>oa_salary.t_insurances_housefund_filing</code>
	 */
	public static final jooq.model.tables.TInsurancesHousefundFiling T_INSURANCES_HOUSEFUND_FILING = new jooq.model.tables.TInsurancesHousefundFiling();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<jooq.model.tables.records.TInsurancesHousefundFilingRecord> getRecordType() {
		return jooq.model.tables.records.TInsurancesHousefundFilingRecord.class;
	}

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.id</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, org.jooq.types.ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.tenant_id</code>. 公司ID | 王默 | 2016-09-14 | 账号模块
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Long> TENANT_ID = createField("tenant_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "公司ID | 王默 | 2016-09-14 | 账号模块");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.user_id</code>. 用户ID | 王默 | 2016-09-14 | 账号模块
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "用户ID | 王默 | 2016-09-14 | 账号模块");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.current_month</code>. 当前时间，社保公积金缴纳的那个月 | 王默 | 2016-09-14 | 逻辑生成
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Integer> CURRENT_MONTH = createField("current_month", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "当前时间，社保公积金缴纳的那个月 | 王默 | 2016-09-14 | 逻辑生成");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.insurances_location_id</code>. 社保参保城市id  | 王默 | 2016-09-14 | t_location.id
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Integer> INSURANCES_LOCATION_ID = createField("insurances_location_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "社保参保城市id  | 王默 | 2016-09-14 | t_location.id");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.housefund_location_id</code>. 公积金城市id | 王默 | 2016-09-14 | t_location.id
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Integer> HOUSEFUND_LOCATION_ID = createField("housefund_location_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "公积金城市id | 王默 | 2016-09-14 | t_location.id");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.insurances_basefee</code>. 社保基数 | 王默 | 2016-09-14 | t_insurance_housefund_config
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Integer> INSURANCES_BASEFEE = createField("insurances_basefee", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "社保基数 | 王默 | 2016-09-14 | t_insurance_housefund_config");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.housefund_basefee</code>. 公积金基数 | 王默 | 2016-09-14 | t_insurance_housefund_config
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Integer> HOUSEFUND_BASEFEE = createField("housefund_basefee", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "公积金基数 | 王默 | 2016-09-14 | t_insurance_housefund_config");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.company_endowment_pay</code>. 公司支付养老保险的数额 | 王默 | 2016-09-14 | t_insurance_housefund_config和t_location联合生成
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Integer> COMPANY_ENDOWMENT_PAY = createField("company_endowment_pay", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "公司支付养老保险的数额 | 王默 | 2016-09-14 | t_insurance_housefund_config和t_location联合生成");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.company_medical_pay</code>. 公司支付医疗保险的数额 | 王默 | 2016-09-14 | t_insurance_housefund_config和t_location联合生成
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Integer> COMPANY_MEDICAL_PAY = createField("company_medical_pay", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "公司支付医疗保险的数额 | 王默 | 2016-09-14 | t_insurance_housefund_config和t_location联合生成");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.company_unemployment_pay</code>. 公司支付失业保险的数额 | 王默 | 2016-09-14 | t_insurance_housefund_config和t_location联合生成
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Integer> COMPANY_UNEMPLOYMENT_PAY = createField("company_unemployment_pay", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "公司支付失业保险的数额 | 王默 | 2016-09-14 | t_insurance_housefund_config和t_location联合生成");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.industrial_injury_proportion</code>. 工伤保险比例 | 王默 | 2016-09-14 | t_insurance_housefund_config
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Integer> INDUSTRIAL_INJURY_PROPORTION = createField("industrial_injury_proportion", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "工伤保险比例 | 王默 | 2016-09-14 | t_insurance_housefund_config");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.company_employment_injury_pay</code>. 公司支付工伤保险的数额 | 王默 | 2016-09-14 | t_insurance_housefund_config
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Integer> COMPANY_EMPLOYMENT_INJURY_PAY = createField("company_employment_injury_pay", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "公司支付工伤保险的数额 | 王默 | 2016-09-14 | t_insurance_housefund_config");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.company_maternity_pay</code>. 公司支付生育保险的数额 | 王默 | 2016-09-14 | t_insurance_housefund_config和t_location联合生成
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Integer> COMPANY_MATERNITY_PAY = createField("company_maternity_pay", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "公司支付生育保险的数额 | 王默 | 2016-09-14 | t_insurance_housefund_config和t_location联合生成");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.employee_endowment_pay</code>. 个人支付养老保险的数额 | 王默 | 2016-09-14 | t_insurance_housefund_config和t_location联合生成
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Integer> EMPLOYEE_ENDOWMENT_PAY = createField("employee_endowment_pay", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "个人支付养老保险的数额 | 王默 | 2016-09-14 | t_insurance_housefund_config和t_location联合生成");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.employee_medical_pay</code>. 个人支付医疗保险的数额 | 王默 | 2016-09-14 | t_insurance_housefund_config和t_location联合生成
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Integer> EMPLOYEE_MEDICAL_PAY = createField("employee_medical_pay", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "个人支付医疗保险的数额 | 王默 | 2016-09-14 | t_insurance_housefund_config和t_location联合生成");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.employee_unemployment_pay</code>. 个人支付失业保险的数额 | 王默 | 2016-09-14 | t_insurance_housefund_config和t_location联合生成
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Integer> EMPLOYEE_UNEMPLOYMENT_PAY = createField("employee_unemployment_pay", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "个人支付失业保险的数额 | 王默 | 2016-09-14 | t_insurance_housefund_config和t_location联合生成");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.company_housefund_proportion</code>. 公司公积金缴纳比例 | 王默 | 2016-09-14 | t_insurance_housefund_config
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Integer> COMPANY_HOUSEFUND_PROPORTION = createField("company_housefund_proportion", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "公司公积金缴纳比例 | 王默 | 2016-09-14 | t_insurance_housefund_config");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.company_housefund_pay</code>. 公司支付住房公积金的数额 | 王默 | 2016-09-14 | t_insurance_housefund_config
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Integer> COMPANY_HOUSEFUND_PAY = createField("company_housefund_pay", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "公司支付住房公积金的数额 | 王默 | 2016-09-14 | t_insurance_housefund_config");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.employee_housefund_proportion</code>. 个人公积金缴纳比例 | 王默 | 2016-09-14 | t_insurance_housefund_config
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Integer> EMPLOYEE_HOUSEFUND_PROPORTION = createField("employee_housefund_proportion", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "个人公积金缴纳比例 | 王默 | 2016-09-14 | t_insurance_housefund_config");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.employee_housefund_pay</code>. 个人支付住房公积金的数额 | 王默 | 2016-09-14 | t_insurance_housefund_config
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Integer> EMPLOYEE_HOUSEFUND_PAY = createField("employee_housefund_pay", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "个人支付住房公积金的数额 | 王默 | 2016-09-14 | t_insurance_housefund_config");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.insurances_begin</code>. 社保缴纳开始月 | 王默 | 2016-09-14 | t_insurance_housefund_config
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Integer> INSURANCES_BEGIN = createField("insurances_begin", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "社保缴纳开始月 | 王默 | 2016-09-14 | t_insurance_housefund_config");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.housefund_begin</code>. 公积金缴纳开始月 | 王默 | 2016-09-14 | t_insurance_housefund_config
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Integer> HOUSEFUND_BEGIN = createField("housefund_begin", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "公积金缴纳开始月 | 王默 | 2016-09-14 | t_insurance_housefund_config");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.residence_type</code>. 户籍类型 | 王默 | 2016-09-14 | t_insurance_housefund_config
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Byte> RESIDENCE_TYPE = createField("residence_type", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "户籍类型 | 王默 | 2016-09-14 | t_insurance_housefund_config");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.insurances_pay_type</code>. 社保缴纳方式 | 王默 | 2016-09-14 | t_insurance_housefund_config
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Byte> INSURANCES_PAY_TYPE = createField("insurances_pay_type", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "社保缴纳方式 | 王默 | 2016-09-14 | t_insurance_housefund_config");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.housefund_pay_type</code>. 公积金缴纳方式 | 王默 | 2016-09-14 | t_insurance_housefund_config
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.lang.Byte> HOUSEFUND_PAY_TYPE = createField("housefund_pay_type", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "公积金缴纳方式 | 王默 | 2016-09-14 | t_insurance_housefund_config");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.create_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>oa_salary.t_insurances_housefund_filing.update_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TInsurancesHousefundFilingRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>oa_salary.t_insurances_housefund_filing</code> table reference
	 */
	public TInsurancesHousefundFiling() {
		this("t_insurances_housefund_filing", null);
	}

	/**
	 * Create an aliased <code>oa_salary.t_insurances_housefund_filing</code> table reference
	 */
	public TInsurancesHousefundFiling(java.lang.String alias) {
		this(alias, jooq.model.tables.TInsurancesHousefundFiling.T_INSURANCES_HOUSEFUND_FILING);
	}

	private TInsurancesHousefundFiling(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TInsurancesHousefundFilingRecord> aliased) {
		this(alias, aliased, null);
	}

	private TInsurancesHousefundFiling(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TInsurancesHousefundFilingRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, jooq.model.OaSalary.OA_SALARY, aliased, parameters, "薪酬模块 | 社保公积金数据表，只记录归档数据 | 王默 | 2016-09-14 | 社保详情页面，和历史归档页面，根据社保公积金配置合成");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<jooq.model.tables.records.TInsurancesHousefundFilingRecord, org.jooq.types.ULong> getIdentity() {
		return jooq.model.Keys.IDENTITY_T_INSURANCES_HOUSEFUND_FILING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<jooq.model.tables.records.TInsurancesHousefundFilingRecord> getPrimaryKey() {
		return jooq.model.Keys.KEY_T_INSURANCES_HOUSEFUND_FILING_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<jooq.model.tables.records.TInsurancesHousefundFilingRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<jooq.model.tables.records.TInsurancesHousefundFilingRecord>>asList(jooq.model.Keys.KEY_T_INSURANCES_HOUSEFUND_FILING_PRIMARY, jooq.model.Keys.KEY_T_INSURANCES_HOUSEFUND_FILING_UIND_TENANT_TIME_USER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public jooq.model.tables.TInsurancesHousefundFiling as(java.lang.String alias) {
		return new jooq.model.tables.TInsurancesHousefundFiling(alias, this);
	}

	/**
	 * Rename this table
	 */
	public jooq.model.tables.TInsurancesHousefundFiling rename(java.lang.String name) {
		return new jooq.model.tables.TInsurancesHousefundFiling(name, null);
	}
}
