/**
 * This class is generated by jOOQ
 */
package jooq.model.tables;

/**
 * This class is generated by jOOQ.
 *
 * @depreciated 薪酬模块 | 记录位置和该位置社保公积金数据 | 邓刚&王默 | 2016-09-14 | 后台系统管理员输入  
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TLocation extends org.jooq.impl.TableImpl<jooq.model.tables.records.TLocationRecord> {

	private static final long serialVersionUID = 1173333874;

	/**
	 * The singleton instance of <code>oa_salary.t_location</code>
	 */
	public static final jooq.model.tables.TLocation T_LOCATION = new jooq.model.tables.TLocation();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<jooq.model.tables.records.TLocationRecord> getRecordType() {
		return jooq.model.tables.records.TLocationRecord.class;
	}

	/**
	 * The column <code>oa_salary.t_location.id</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TLocationRecord, org.jooq.types.UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_location.city</code>. 市级行政单位 | 邓刚&王默 | 2016-09-14 | 
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TLocationRecord, java.lang.String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "市级行政单位 | 邓刚&王默 | 2016-09-14 | ");

	/**
	 * The column <code>oa_salary.t_location.cname</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TLocationRecord, java.lang.String> CNAME = createField("cname", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_location.month</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TLocationRecord, java.lang.String> MONTH = createField("month", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_location.pname</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TLocationRecord, java.lang.String> PNAME = createField("pname", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_location.prov</code>. 省级行政单位  | 邓刚&王默 | 2016-09-14 | 
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TLocationRecord, java.lang.String> PROV = createField("prov", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "省级行政单位  | 邓刚&王默 | 2016-09-14 | ");

	/**
	 * The column <code>oa_salary.t_location.region</code>. 县级行政单位 | 邓刚&王默 | 2016-09-14 | 
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TLocationRecord, java.lang.String> REGION = createField("region", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "县级行政单位 | 邓刚&王默 | 2016-09-14 | ");

	/**
	 * The column <code>oa_salary.t_location.rule</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TLocationRecord, java.lang.Integer> RULE = createField("rule", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_location.subdl</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TLocationRecord, java.lang.Integer> SUBDL = createField("subdl", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_location.timestamp</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TLocationRecord, java.lang.String> TIMESTAMP = createField("timestamp", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_location.last_date</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TLocationRecord, java.lang.String> LAST_DATE = createField("last_date", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_location.create_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TLocationRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>oa_salary.t_location.update_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TLocationRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>oa_salary.t_location</code> table reference
	 */
	public TLocation() {
		this("t_location", null);
	}

	/**
	 * Create an aliased <code>oa_salary.t_location</code> table reference
	 */
	public TLocation(java.lang.String alias) {
		this(alias, jooq.model.tables.TLocation.T_LOCATION);
	}

	private TLocation(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TLocationRecord> aliased) {
		this(alias, aliased, null);
	}

	private TLocation(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TLocationRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, jooq.model.OaSalary.OA_SALARY, aliased, parameters, "@depreciated 薪酬模块 | 记录位置和该位置社保公积金数据 | 邓刚&王默 | 2016-09-14 | 后台系统管理员输入  ");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<jooq.model.tables.records.TLocationRecord, org.jooq.types.UInteger> getIdentity() {
		return jooq.model.Keys.IDENTITY_T_LOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<jooq.model.tables.records.TLocationRecord> getPrimaryKey() {
		return jooq.model.Keys.KEY_T_LOCATION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<jooq.model.tables.records.TLocationRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<jooq.model.tables.records.TLocationRecord>>asList(jooq.model.Keys.KEY_T_LOCATION_PRIMARY, jooq.model.Keys.KEY_T_LOCATION_IDX_LOCATION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public jooq.model.tables.TLocation as(java.lang.String alias) {
		return new jooq.model.tables.TLocation(alias, this);
	}

	/**
	 * Rename this table
	 */
	public jooq.model.tables.TLocation rename(java.lang.String name) {
		return new jooq.model.tables.TLocation(name, null);
	}
}
