/**
 * This class is generated by jOOQ
 */
package jooq.model.tables;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 计薪设置 | 王默 | 2016-09-14 | 计薪设置页面，用户界面操作
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSalaryCalculationConfig extends org.jooq.impl.TableImpl<jooq.model.tables.records.TSalaryCalculationConfigRecord> {

	private static final long serialVersionUID = 210091311;

	/**
	 * The singleton instance of <code>oa_salary.t_salary_calculation_config</code>
	 */
	public static final jooq.model.tables.TSalaryCalculationConfig T_SALARY_CALCULATION_CONFIG = new jooq.model.tables.TSalaryCalculationConfig();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<jooq.model.tables.records.TSalaryCalculationConfigRecord> getRecordType() {
		return jooq.model.tables.records.TSalaryCalculationConfigRecord.class;
	}

	/**
	 * The column <code>oa_salary.t_salary_calculation_config.id</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TSalaryCalculationConfigRecord, org.jooq.types.UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_salary_calculation_config.tenant_id</code>. 公司ID | 王默 | 2016-09-14 | 账号模块
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TSalaryCalculationConfigRecord, java.lang.Long> TENANT_ID = createField("tenant_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "公司ID | 王默 | 2016-09-14 | 账号模块");

	/**
	 * The column <code>oa_salary.t_salary_calculation_config.calculation_start</code>. 计薪开始是几号 | 王默 | 2016-09-14 | 用户界面操作
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TSalaryCalculationConfigRecord, org.jooq.types.UByte> CALCULATION_START = createField("calculation_start", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "计薪开始是几号 | 王默 | 2016-09-14 | 用户界面操作");

	/**
	 * The column <code>oa_salary.t_salary_calculation_config.calculation_end</code>. 计薪结束是几号 | 王默 | 2016-09-14 | 用户界面操作
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TSalaryCalculationConfigRecord, org.jooq.types.UByte> CALCULATION_END = createField("calculation_end", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "计薪结束是几号 | 王默 | 2016-09-14 | 用户界面操作");

	/**
	 * The column <code>oa_salary.t_salary_calculation_config.is_calculation_time_set</code>. 是不是已经设置过计薪开始日期，设置过之后不能更改 | 王默 | 2016-09-14 | @1:未设置 @2:已设置 | 后台处理逻辑
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TSalaryCalculationConfigRecord, org.jooq.types.UByte> IS_CALCULATION_TIME_SET = createField("is_calculation_time_set", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false).defaulted(true), this, "是不是已经设置过计薪开始日期，设置过之后不能更改 | 王默 | 2016-09-14 | @1:未设置 @2:已设置 | 后台处理逻辑");

	/**
	 * The column <code>oa_salary.t_salary_calculation_config.payoff_month</code>. 发薪月份 | 王默 | 2016-09-14 | @0:本月发薪 @1:下月发薪 | 用户界面操作，选择
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TSalaryCalculationConfigRecord, org.jooq.types.UByte> PAYOFF_MONTH = createField("payoff_month", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "发薪月份 | 王默 | 2016-09-14 | @0:本月发薪 @1:下月发薪 | 用户界面操作，选择");

	/**
	 * The column <code>oa_salary.t_salary_calculation_config.payoff_day</code>. 发薪是几号 | 王默 | 2016-09-14 | 用户界面操作，选择
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TSalaryCalculationConfigRecord, org.jooq.types.UByte> PAYOFF_DAY = createField("payoff_day", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "发薪是几号 | 王默 | 2016-09-14 | 用户界面操作，选择");

	/**
	 * The column <code>oa_salary.t_salary_calculation_config.calculation_way</code>. 计薪方式 | 王默 | 2016-09-14 | @1:11天为临界点 @2:21.75天为临界点 @3:按实际工作日计算 | 用户界面操作，选择
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TSalaryCalculationConfigRecord, org.jooq.types.UByte> CALCULATION_WAY = createField("calculation_way", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false).defaulted(true), this, "计薪方式 | 王默 | 2016-09-14 | @1:11天为临界点 @2:21.75天为临界点 @3:按实际工作日计算 | 用户界面操作，选择");

	/**
	 * The column <code>oa_salary.t_salary_calculation_config.insurances_data_source</code>. 社保数据源 | 王默 | 2016-09-14 | @1:社保模块 @2:不计算社保 | 用户界面操作，选择
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TSalaryCalculationConfigRecord, org.jooq.types.UByte> INSURANCES_DATA_SOURCE = createField("insurances_data_source", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false).defaulted(true), this, "社保数据源 | 王默 | 2016-09-14 | @1:社保模块 @2:不计算社保 | 用户界面操作，选择");

	/**
	 * The column <code>oa_salary.t_salary_calculation_config.attendance_data_source</code>. 考勤数据源 | 王默 | 2016-09-14 | @1:考勤模块 @2:自主上传 | 用户界面操作，选择 
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TSalaryCalculationConfigRecord, org.jooq.types.UByte> ATTENDANCE_DATA_SOURCE = createField("attendance_data_source", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false).defaulted(true), this, "考勤数据源 | 王默 | 2016-09-14 | @1:考勤模块 @2:自主上传 | 用户界面操作，选择 ");

	/**
	 * The column <code>oa_salary.t_salary_calculation_config.create_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TSalaryCalculationConfigRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>oa_salary.t_salary_calculation_config.update_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TSalaryCalculationConfigRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>oa_salary.t_salary_calculation_config</code> table reference
	 */
	public TSalaryCalculationConfig() {
		this("t_salary_calculation_config", null);
	}

	/**
	 * Create an aliased <code>oa_salary.t_salary_calculation_config</code> table reference
	 */
	public TSalaryCalculationConfig(java.lang.String alias) {
		this(alias, jooq.model.tables.TSalaryCalculationConfig.T_SALARY_CALCULATION_CONFIG);
	}

	private TSalaryCalculationConfig(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TSalaryCalculationConfigRecord> aliased) {
		this(alias, aliased, null);
	}

	private TSalaryCalculationConfig(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TSalaryCalculationConfigRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, jooq.model.OaSalary.OA_SALARY, aliased, parameters, "薪酬模块 | 计薪设置 | 王默 | 2016-09-14 | 计薪设置页面，用户界面操作");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<jooq.model.tables.records.TSalaryCalculationConfigRecord, org.jooq.types.UInteger> getIdentity() {
		return jooq.model.Keys.IDENTITY_T_SALARY_CALCULATION_CONFIG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<jooq.model.tables.records.TSalaryCalculationConfigRecord> getPrimaryKey() {
		return jooq.model.Keys.KEY_T_SALARY_CALCULATION_CONFIG_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<jooq.model.tables.records.TSalaryCalculationConfigRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<jooq.model.tables.records.TSalaryCalculationConfigRecord>>asList(jooq.model.Keys.KEY_T_SALARY_CALCULATION_CONFIG_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public jooq.model.tables.TSalaryCalculationConfig as(java.lang.String alias) {
		return new jooq.model.tables.TSalaryCalculationConfig(alias, this);
	}

	/**
	 * Rename this table
	 */
	public jooq.model.tables.TSalaryCalculationConfig rename(java.lang.String name) {
		return new jooq.model.tables.TSalaryCalculationConfig(name, null);
	}
}
