/**
 * This class is generated by jOOQ
 */
package jooq.model.tables;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 个人薪酬计算中一些动态变化的东西 | 王默 | 2016-09-14 | 个人薪酬详情页面，用户界面操作
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSalaryConfig extends org.jooq.impl.TableImpl<jooq.model.tables.records.TSalaryConfigRecord> {

	private static final long serialVersionUID = -896321280;

	/**
	 * The singleton instance of <code>oa_salary.t_salary_config</code>
	 */
	public static final jooq.model.tables.TSalaryConfig T_SALARY_CONFIG = new jooq.model.tables.TSalaryConfig();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<jooq.model.tables.records.TSalaryConfigRecord> getRecordType() {
		return jooq.model.tables.records.TSalaryConfigRecord.class;
	}

	/**
	 * The column <code>oa_salary.t_salary_config.id</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TSalaryConfigRecord, org.jooq.types.ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>oa_salary.t_salary_config.tenant_id</code>. 公司ID | 王默 | 2016-09-14 | 账号模块
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TSalaryConfigRecord, java.lang.Long> TENANT_ID = createField("tenant_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "公司ID | 王默 | 2016-09-14 | 账号模块");

	/**
	 * The column <code>oa_salary.t_salary_config.user_id</code>. 用户ID | 王默 | 2016-09-14 | 账号模块
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TSalaryConfigRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "用户ID | 王默 | 2016-09-14 | 账号模块");

	/**
	 * The column <code>oa_salary.t_salary_config.attendance_days</code>. 这个月出勤多少天 | 王默 | 2016-09-14 | 输入？？？
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TSalaryConfigRecord, java.lang.Double> ATTENDANCE_DAYS = createField("attendance_days", org.jooq.impl.SQLDataType.FLOAT.nullable(false).defaulted(true), this, "这个月出勤多少天 | 王默 | 2016-09-14 | 输入？？？");

	/**
	 * The column <code>oa_salary.t_salary_config.before_tax_add_or_deduct</code>. 税前补扣款 | 王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TSalaryConfigRecord, java.lang.Integer> BEFORE_TAX_ADD_OR_DEDUCT = createField("before_tax_add_or_deduct", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "税前补扣款 | 王默 | 2016-09-14 | 用户界面操作，输入");

	/**
	 * The column <code>oa_salary.t_salary_config.after_tax_add_or_deduct</code>. 税后补扣款 | 王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TSalaryConfigRecord, java.lang.Integer> AFTER_TAX_ADD_OR_DEDUCT = createField("after_tax_add_or_deduct", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "税后补扣款 | 王默 | 2016-09-14 | 用户界面操作，输入");

	/**
	 * The column <code>oa_salary.t_salary_config.create_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TSalaryConfigRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>oa_salary.t_salary_config.update_time</code>.
	 */
	public final org.jooq.TableField<jooq.model.tables.records.TSalaryConfigRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>oa_salary.t_salary_config</code> table reference
	 */
	public TSalaryConfig() {
		this("t_salary_config", null);
	}

	/**
	 * Create an aliased <code>oa_salary.t_salary_config</code> table reference
	 */
	public TSalaryConfig(java.lang.String alias) {
		this(alias, jooq.model.tables.TSalaryConfig.T_SALARY_CONFIG);
	}

	private TSalaryConfig(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TSalaryConfigRecord> aliased) {
		this(alias, aliased, null);
	}

	private TSalaryConfig(java.lang.String alias, org.jooq.Table<jooq.model.tables.records.TSalaryConfigRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, jooq.model.OaSalary.OA_SALARY, aliased, parameters, "薪酬模块 | 个人薪酬计算中一些动态变化的东西 | 王默 | 2016-09-14 | 个人薪酬详情页面，用户界面操作");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<jooq.model.tables.records.TSalaryConfigRecord, org.jooq.types.ULong> getIdentity() {
		return jooq.model.Keys.IDENTITY_T_SALARY_CONFIG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<jooq.model.tables.records.TSalaryConfigRecord> getPrimaryKey() {
		return jooq.model.Keys.KEY_T_SALARY_CONFIG_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<jooq.model.tables.records.TSalaryConfigRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<jooq.model.tables.records.TSalaryConfigRecord>>asList(jooq.model.Keys.KEY_T_SALARY_CONFIG_PRIMARY, jooq.model.Keys.KEY_T_SALARY_CONFIG_UIND_TENANT_USER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public jooq.model.tables.TSalaryConfig as(java.lang.String alias) {
		return new jooq.model.tables.TSalaryConfig(alias, this);
	}

	/**
	 * Rename this table
	 */
	public jooq.model.tables.TSalaryConfig rename(java.lang.String name) {
		return new jooq.model.tables.TSalaryConfig(name, null);
	}
}
