/**
 * This class is generated by jOOQ
 */
package jooq.model;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>oa_salary</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<jooq.model.tables.records.TAllowancePlanRecord, org.jooq.types.UInteger> IDENTITY_T_ALLOWANCE_PLAN = Identities0.IDENTITY_T_ALLOWANCE_PLAN;
	public static final org.jooq.Identity<jooq.model.tables.records.TAttendanceDataRecord, org.jooq.types.ULong> IDENTITY_T_ATTENDANCE_DATA = Identities0.IDENTITY_T_ATTENDANCE_DATA;
	public static final org.jooq.Identity<jooq.model.tables.records.TBasicSalaryRecord, org.jooq.types.ULong> IDENTITY_T_BASIC_SALARY = Identities0.IDENTITY_T_BASIC_SALARY;
	public static final org.jooq.Identity<jooq.model.tables.records.TBasicSalaryAdjustmentRecord, org.jooq.types.ULong> IDENTITY_T_BASIC_SALARY_ADJUSTMENT = Identities0.IDENTITY_T_BASIC_SALARY_ADJUSTMENT;
	public static final org.jooq.Identity<jooq.model.tables.records.TBasicSalaryTypeRecord, org.jooq.types.ULong> IDENTITY_T_BASIC_SALARY_TYPE = Identities0.IDENTITY_T_BASIC_SALARY_TYPE;
	public static final org.jooq.Identity<jooq.model.tables.records.TBonusRecord, org.jooq.types.ULong> IDENTITY_T_BONUS = Identities0.IDENTITY_T_BONUS;
	public static final org.jooq.Identity<jooq.model.tables.records.TBonusApportionedRecord, org.jooq.types.UInteger> IDENTITY_T_BONUS_APPORTIONED = Identities0.IDENTITY_T_BONUS_APPORTIONED;
	public static final org.jooq.Identity<jooq.model.tables.records.TBonusTypeRecord, org.jooq.types.UInteger> IDENTITY_T_BONUS_TYPE = Identities0.IDENTITY_T_BONUS_TYPE;
	public static final org.jooq.Identity<jooq.model.tables.records.TFilingHistoryRecord, org.jooq.types.ULong> IDENTITY_T_FILING_HISTORY = Identities0.IDENTITY_T_FILING_HISTORY;
	public static final org.jooq.Identity<jooq.model.tables.records.TInsurancesHousefundConfigRecord, org.jooq.types.ULong> IDENTITY_T_INSURANCES_HOUSEFUND_CONFIG = Identities0.IDENTITY_T_INSURANCES_HOUSEFUND_CONFIG;
	public static final org.jooq.Identity<jooq.model.tables.records.TInsurancesHousefundFilingRecord, org.jooq.types.ULong> IDENTITY_T_INSURANCES_HOUSEFUND_FILING = Identities0.IDENTITY_T_INSURANCES_HOUSEFUND_FILING;
	public static final org.jooq.Identity<jooq.model.tables.records.TLocationRecord, org.jooq.types.UInteger> IDENTITY_T_LOCATION = Identities0.IDENTITY_T_LOCATION;
	public static final org.jooq.Identity<jooq.model.tables.records.TSalaryCalculationConfigRecord, org.jooq.types.UInteger> IDENTITY_T_SALARY_CALCULATION_CONFIG = Identities0.IDENTITY_T_SALARY_CALCULATION_CONFIG;
	public static final org.jooq.Identity<jooq.model.tables.records.TSalaryConfigRecord, org.jooq.types.ULong> IDENTITY_T_SALARY_CONFIG = Identities0.IDENTITY_T_SALARY_CONFIG;
	public static final org.jooq.Identity<jooq.model.tables.records.TSupplementaryHousefundRecord, org.jooq.types.ULong> IDENTITY_T_SUPPLEMENTARY_HOUSEFUND = Identities0.IDENTITY_T_SUPPLEMENTARY_HOUSEFUND;
	public static final org.jooq.Identity<jooq.model.tables.records.TSupplementaryInsurancesRecord, org.jooq.types.ULong> IDENTITY_T_SUPPLEMENTARY_INSURANCES = Identities0.IDENTITY_T_SUPPLEMENTARY_INSURANCES;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<jooq.model.tables.records.TAllowanceAdaptedRecord> KEY_T_ALLOWANCE_ADAPTED_PRIMARY = UniqueKeys0.KEY_T_ALLOWANCE_ADAPTED_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TAllowancePlanRecord> KEY_T_ALLOWANCE_PLAN_PRIMARY = UniqueKeys0.KEY_T_ALLOWANCE_PLAN_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TAttendanceDataRecord> KEY_T_ATTENDANCE_DATA_PRIMARY = UniqueKeys0.KEY_T_ATTENDANCE_DATA_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TBasicSalaryRecord> KEY_T_BASIC_SALARY_PRIMARY = UniqueKeys0.KEY_T_BASIC_SALARY_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TBasicSalaryAdjustmentRecord> KEY_T_BASIC_SALARY_ADJUSTMENT_PRIMARY = UniqueKeys0.KEY_T_BASIC_SALARY_ADJUSTMENT_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TBasicSalaryTypeRecord> KEY_T_BASIC_SALARY_TYPE_PRIMARY = UniqueKeys0.KEY_T_BASIC_SALARY_TYPE_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TBonusRecord> KEY_T_BONUS_PRIMARY = UniqueKeys0.KEY_T_BONUS_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TBonusApportionedRecord> KEY_T_BONUS_APPORTIONED_PRIMARY = UniqueKeys0.KEY_T_BONUS_APPORTIONED_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TBonusApportionedRecord> KEY_T_BONUS_APPORTIONED_UIND_TENANT_YEAR = UniqueKeys0.KEY_T_BONUS_APPORTIONED_UIND_TENANT_YEAR;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TBonusTypeRecord> KEY_T_BONUS_TYPE_PRIMARY = UniqueKeys0.KEY_T_BONUS_TYPE_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TFilingHistoryRecord> KEY_T_FILING_HISTORY_PRIMARY = UniqueKeys0.KEY_T_FILING_HISTORY_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TFilingHistoryRecord> KEY_T_FILING_HISTORY_UIND_TENANT_DATE = UniqueKeys0.KEY_T_FILING_HISTORY_UIND_TENANT_DATE;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TInsurancesHousefundConfigRecord> KEY_T_INSURANCES_HOUSEFUND_CONFIG_PRIMARY = UniqueKeys0.KEY_T_INSURANCES_HOUSEFUND_CONFIG_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TInsurancesHousefundConfigRecord> KEY_T_INSURANCES_HOUSEFUND_CONFIG_UIND_TENANT_USER = UniqueKeys0.KEY_T_INSURANCES_HOUSEFUND_CONFIG_UIND_TENANT_USER;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TInsurancesHousefundFilingRecord> KEY_T_INSURANCES_HOUSEFUND_FILING_PRIMARY = UniqueKeys0.KEY_T_INSURANCES_HOUSEFUND_FILING_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TInsurancesHousefundFilingRecord> KEY_T_INSURANCES_HOUSEFUND_FILING_UIND_TENANT_TIME_USER = UniqueKeys0.KEY_T_INSURANCES_HOUSEFUND_FILING_UIND_TENANT_TIME_USER;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TLocationRecord> KEY_T_LOCATION_PRIMARY = UniqueKeys0.KEY_T_LOCATION_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TSalaryCalculationConfigRecord> KEY_T_SALARY_CALCULATION_CONFIG_PRIMARY = UniqueKeys0.KEY_T_SALARY_CALCULATION_CONFIG_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TSalaryConfigRecord> KEY_T_SALARY_CONFIG_PRIMARY = UniqueKeys0.KEY_T_SALARY_CONFIG_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TSalaryConfigRecord> KEY_T_SALARY_CONFIG_UIND_TENANT_USER = UniqueKeys0.KEY_T_SALARY_CONFIG_UIND_TENANT_USER;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TSupplementaryHousefundRecord> KEY_T_SUPPLEMENTARY_HOUSEFUND_PRIMARY = UniqueKeys0.KEY_T_SUPPLEMENTARY_HOUSEFUND_PRIMARY;
	public static final org.jooq.UniqueKey<jooq.model.tables.records.TSupplementaryInsurancesRecord> KEY_T_SUPPLEMENTARY_INSURANCES_PRIMARY = UniqueKeys0.KEY_T_SUPPLEMENTARY_INSURANCES_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<jooq.model.tables.records.TAllowancePlanRecord, org.jooq.types.UInteger> IDENTITY_T_ALLOWANCE_PLAN = createIdentity(jooq.model.tables.TAllowancePlan.T_ALLOWANCE_PLAN, jooq.model.tables.TAllowancePlan.T_ALLOWANCE_PLAN.ID);
		public static org.jooq.Identity<jooq.model.tables.records.TAttendanceDataRecord, org.jooq.types.ULong> IDENTITY_T_ATTENDANCE_DATA = createIdentity(jooq.model.tables.TAttendanceData.T_ATTENDANCE_DATA, jooq.model.tables.TAttendanceData.T_ATTENDANCE_DATA.ID);
		public static org.jooq.Identity<jooq.model.tables.records.TBasicSalaryRecord, org.jooq.types.ULong> IDENTITY_T_BASIC_SALARY = createIdentity(jooq.model.tables.TBasicSalary.T_BASIC_SALARY, jooq.model.tables.TBasicSalary.T_BASIC_SALARY.ID);
		public static org.jooq.Identity<jooq.model.tables.records.TBasicSalaryAdjustmentRecord, org.jooq.types.ULong> IDENTITY_T_BASIC_SALARY_ADJUSTMENT = createIdentity(jooq.model.tables.TBasicSalaryAdjustment.T_BASIC_SALARY_ADJUSTMENT, jooq.model.tables.TBasicSalaryAdjustment.T_BASIC_SALARY_ADJUSTMENT.ID);
		public static org.jooq.Identity<jooq.model.tables.records.TBasicSalaryTypeRecord, org.jooq.types.ULong> IDENTITY_T_BASIC_SALARY_TYPE = createIdentity(jooq.model.tables.TBasicSalaryType.T_BASIC_SALARY_TYPE, jooq.model.tables.TBasicSalaryType.T_BASIC_SALARY_TYPE.ID);
		public static org.jooq.Identity<jooq.model.tables.records.TBonusRecord, org.jooq.types.ULong> IDENTITY_T_BONUS = createIdentity(jooq.model.tables.TBonus.T_BONUS, jooq.model.tables.TBonus.T_BONUS.ID);
		public static org.jooq.Identity<jooq.model.tables.records.TBonusApportionedRecord, org.jooq.types.UInteger> IDENTITY_T_BONUS_APPORTIONED = createIdentity(jooq.model.tables.TBonusApportioned.T_BONUS_APPORTIONED, jooq.model.tables.TBonusApportioned.T_BONUS_APPORTIONED.ID);
		public static org.jooq.Identity<jooq.model.tables.records.TBonusTypeRecord, org.jooq.types.UInteger> IDENTITY_T_BONUS_TYPE = createIdentity(jooq.model.tables.TBonusType.T_BONUS_TYPE, jooq.model.tables.TBonusType.T_BONUS_TYPE.ID);
		public static org.jooq.Identity<jooq.model.tables.records.TFilingHistoryRecord, org.jooq.types.ULong> IDENTITY_T_FILING_HISTORY = createIdentity(jooq.model.tables.TFilingHistory.T_FILING_HISTORY, jooq.model.tables.TFilingHistory.T_FILING_HISTORY.ID);
		public static org.jooq.Identity<jooq.model.tables.records.TInsurancesHousefundConfigRecord, org.jooq.types.ULong> IDENTITY_T_INSURANCES_HOUSEFUND_CONFIG = createIdentity(jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG, jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG.ID);
		public static org.jooq.Identity<jooq.model.tables.records.TInsurancesHousefundFilingRecord, org.jooq.types.ULong> IDENTITY_T_INSURANCES_HOUSEFUND_FILING = createIdentity(jooq.model.tables.TInsurancesHousefundFiling.T_INSURANCES_HOUSEFUND_FILING, jooq.model.tables.TInsurancesHousefundFiling.T_INSURANCES_HOUSEFUND_FILING.ID);
		public static org.jooq.Identity<jooq.model.tables.records.TLocationRecord, org.jooq.types.UInteger> IDENTITY_T_LOCATION = createIdentity(jooq.model.tables.TLocation.T_LOCATION, jooq.model.tables.TLocation.T_LOCATION.ID);
		public static org.jooq.Identity<jooq.model.tables.records.TSalaryCalculationConfigRecord, org.jooq.types.UInteger> IDENTITY_T_SALARY_CALCULATION_CONFIG = createIdentity(jooq.model.tables.TSalaryCalculationConfig.T_SALARY_CALCULATION_CONFIG, jooq.model.tables.TSalaryCalculationConfig.T_SALARY_CALCULATION_CONFIG.ID);
		public static org.jooq.Identity<jooq.model.tables.records.TSalaryConfigRecord, org.jooq.types.ULong> IDENTITY_T_SALARY_CONFIG = createIdentity(jooq.model.tables.TSalaryConfig.T_SALARY_CONFIG, jooq.model.tables.TSalaryConfig.T_SALARY_CONFIG.ID);
		public static org.jooq.Identity<jooq.model.tables.records.TSupplementaryHousefundRecord, org.jooq.types.ULong> IDENTITY_T_SUPPLEMENTARY_HOUSEFUND = createIdentity(jooq.model.tables.TSupplementaryHousefund.T_SUPPLEMENTARY_HOUSEFUND, jooq.model.tables.TSupplementaryHousefund.T_SUPPLEMENTARY_HOUSEFUND.ID);
		public static org.jooq.Identity<jooq.model.tables.records.TSupplementaryInsurancesRecord, org.jooq.types.ULong> IDENTITY_T_SUPPLEMENTARY_INSURANCES = createIdentity(jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES, jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TAllowanceAdaptedRecord> KEY_T_ALLOWANCE_ADAPTED_PRIMARY = createUniqueKey(jooq.model.tables.TAllowanceAdapted.T_ALLOWANCE_ADAPTED, jooq.model.tables.TAllowanceAdapted.T_ALLOWANCE_ADAPTED.ID);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TAllowancePlanRecord> KEY_T_ALLOWANCE_PLAN_PRIMARY = createUniqueKey(jooq.model.tables.TAllowancePlan.T_ALLOWANCE_PLAN, jooq.model.tables.TAllowancePlan.T_ALLOWANCE_PLAN.ID);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TAttendanceDataRecord> KEY_T_ATTENDANCE_DATA_PRIMARY = createUniqueKey(jooq.model.tables.TAttendanceData.T_ATTENDANCE_DATA, jooq.model.tables.TAttendanceData.T_ATTENDANCE_DATA.ID);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TBasicSalaryRecord> KEY_T_BASIC_SALARY_PRIMARY = createUniqueKey(jooq.model.tables.TBasicSalary.T_BASIC_SALARY, jooq.model.tables.TBasicSalary.T_BASIC_SALARY.ID);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TBasicSalaryAdjustmentRecord> KEY_T_BASIC_SALARY_ADJUSTMENT_PRIMARY = createUniqueKey(jooq.model.tables.TBasicSalaryAdjustment.T_BASIC_SALARY_ADJUSTMENT, jooq.model.tables.TBasicSalaryAdjustment.T_BASIC_SALARY_ADJUSTMENT.ID);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TBasicSalaryTypeRecord> KEY_T_BASIC_SALARY_TYPE_PRIMARY = createUniqueKey(jooq.model.tables.TBasicSalaryType.T_BASIC_SALARY_TYPE, jooq.model.tables.TBasicSalaryType.T_BASIC_SALARY_TYPE.ID);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TBonusRecord> KEY_T_BONUS_PRIMARY = createUniqueKey(jooq.model.tables.TBonus.T_BONUS, jooq.model.tables.TBonus.T_BONUS.ID);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TBonusApportionedRecord> KEY_T_BONUS_APPORTIONED_PRIMARY = createUniqueKey(jooq.model.tables.TBonusApportioned.T_BONUS_APPORTIONED, jooq.model.tables.TBonusApportioned.T_BONUS_APPORTIONED.ID);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TBonusApportionedRecord> KEY_T_BONUS_APPORTIONED_UIND_TENANT_YEAR = createUniqueKey(jooq.model.tables.TBonusApportioned.T_BONUS_APPORTIONED, jooq.model.tables.TBonusApportioned.T_BONUS_APPORTIONED.TENANT_ID, jooq.model.tables.TBonusApportioned.T_BONUS_APPORTIONED.YEAR);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TBonusTypeRecord> KEY_T_BONUS_TYPE_PRIMARY = createUniqueKey(jooq.model.tables.TBonusType.T_BONUS_TYPE, jooq.model.tables.TBonusType.T_BONUS_TYPE.ID);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TFilingHistoryRecord> KEY_T_FILING_HISTORY_PRIMARY = createUniqueKey(jooq.model.tables.TFilingHistory.T_FILING_HISTORY, jooq.model.tables.TFilingHistory.T_FILING_HISTORY.ID);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TFilingHistoryRecord> KEY_T_FILING_HISTORY_UIND_TENANT_DATE = createUniqueKey(jooq.model.tables.TFilingHistory.T_FILING_HISTORY, jooq.model.tables.TFilingHistory.T_FILING_HISTORY.TENANT_ID, jooq.model.tables.TFilingHistory.T_FILING_HISTORY.FILING_TIME);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TInsurancesHousefundConfigRecord> KEY_T_INSURANCES_HOUSEFUND_CONFIG_PRIMARY = createUniqueKey(jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG, jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG.ID);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TInsurancesHousefundConfigRecord> KEY_T_INSURANCES_HOUSEFUND_CONFIG_UIND_TENANT_USER = createUniqueKey(jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG, jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG.TENANT_ID, jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG.USER_ID);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TInsurancesHousefundFilingRecord> KEY_T_INSURANCES_HOUSEFUND_FILING_PRIMARY = createUniqueKey(jooq.model.tables.TInsurancesHousefundFiling.T_INSURANCES_HOUSEFUND_FILING, jooq.model.tables.TInsurancesHousefundFiling.T_INSURANCES_HOUSEFUND_FILING.ID);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TInsurancesHousefundFilingRecord> KEY_T_INSURANCES_HOUSEFUND_FILING_UIND_TENANT_TIME_USER = createUniqueKey(jooq.model.tables.TInsurancesHousefundFiling.T_INSURANCES_HOUSEFUND_FILING, jooq.model.tables.TInsurancesHousefundFiling.T_INSURANCES_HOUSEFUND_FILING.TENANT_ID, jooq.model.tables.TInsurancesHousefundFiling.T_INSURANCES_HOUSEFUND_FILING.CURRENT_MONTH, jooq.model.tables.TInsurancesHousefundFiling.T_INSURANCES_HOUSEFUND_FILING.USER_ID);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TLocationRecord> KEY_T_LOCATION_PRIMARY = createUniqueKey(jooq.model.tables.TLocation.T_LOCATION, jooq.model.tables.TLocation.T_LOCATION.ID);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TSalaryCalculationConfigRecord> KEY_T_SALARY_CALCULATION_CONFIG_PRIMARY = createUniqueKey(jooq.model.tables.TSalaryCalculationConfig.T_SALARY_CALCULATION_CONFIG, jooq.model.tables.TSalaryCalculationConfig.T_SALARY_CALCULATION_CONFIG.ID);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TSalaryConfigRecord> KEY_T_SALARY_CONFIG_PRIMARY = createUniqueKey(jooq.model.tables.TSalaryConfig.T_SALARY_CONFIG, jooq.model.tables.TSalaryConfig.T_SALARY_CONFIG.ID);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TSalaryConfigRecord> KEY_T_SALARY_CONFIG_UIND_TENANT_USER = createUniqueKey(jooq.model.tables.TSalaryConfig.T_SALARY_CONFIG, jooq.model.tables.TSalaryConfig.T_SALARY_CONFIG.TENANT_ID, jooq.model.tables.TSalaryConfig.T_SALARY_CONFIG.USER_ID);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TSupplementaryHousefundRecord> KEY_T_SUPPLEMENTARY_HOUSEFUND_PRIMARY = createUniqueKey(jooq.model.tables.TSupplementaryHousefund.T_SUPPLEMENTARY_HOUSEFUND, jooq.model.tables.TSupplementaryHousefund.T_SUPPLEMENTARY_HOUSEFUND.ID);
		public static final org.jooq.UniqueKey<jooq.model.tables.records.TSupplementaryInsurancesRecord> KEY_T_SUPPLEMENTARY_INSURANCES_PRIMARY = createUniqueKey(jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES, jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.ID);
	}
}
