/**
 * This class is generated by jOOQ
 */
package jooq.model.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 存储津贴适用的用户或部分 | 邓刚&王默 | 2016-09-14 | 津贴设置页面，用户界面操作
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAllowanceAdaptedRecord extends org.jooq.impl.UpdatableRecordImpl<jooq.model.tables.records.TAllowanceAdaptedRecord> implements org.jooq.Record7<org.jooq.types.UInteger, java.lang.Long, org.jooq.types.UInteger, org.jooq.types.UByte, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 1596219732;

	/**
	 * Setter for <code>oa_salary.t_allowance_adapted.id</code>.
	 */
	public void setId(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>oa_salary.t_allowance_adapted.id</code>.
	 */
	public org.jooq.types.UInteger getId() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>oa_salary.t_allowance_adapted.tenant_id</code>.
	 */
	public void setTenantId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>oa_salary.t_allowance_adapted.tenant_id</code>.
	 */
	public java.lang.Long getTenantId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>oa_salary.t_allowance_adapted.allowance_plan_id</code>. 津贴方案id | 邓刚&王默 | 2016-09-14 | 用户存储津贴设置时候，将其所选部门或员工（多个）存入数据库，t_allowance_plan.id
	 */
	public void setAllowancePlanId(org.jooq.types.UInteger value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>oa_salary.t_allowance_adapted.allowance_plan_id</code>. 津贴方案id | 邓刚&王默 | 2016-09-14 | 用户存储津贴设置时候，将其所选部门或员工（多个）存入数据库，t_allowance_plan.id
	 */
	public org.jooq.types.UInteger getAllowancePlanId() {
		return (org.jooq.types.UInteger) getValue(2);
	}

	/**
	 * Setter for <code>oa_salary.t_allowance_adapted.is_adapt_to_user</code>. 存储的department_or_user_id 是departmentid还是userid | 邓刚&王默 | 2016-09-14 | @1:适用与单个用户 @2:适用于整个部门 | 用户存储津贴设置时候，将其所选部门或员工（多个）存入数据库，此字段来自于后台程序
	 */
	public void setIsAdaptToUser(org.jooq.types.UByte value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>oa_salary.t_allowance_adapted.is_adapt_to_user</code>. 存储的department_or_user_id 是departmentid还是userid | 邓刚&王默 | 2016-09-14 | @1:适用与单个用户 @2:适用于整个部门 | 用户存储津贴设置时候，将其所选部门或员工（多个）存入数据库，此字段来自于后台程序
	 */
	public org.jooq.types.UByte getIsAdaptToUser() {
		return (org.jooq.types.UByte) getValue(3);
	}

	/**
	 * Setter for <code>oa_salary.t_allowance_adapted.department_or_user_id</code>. 部门ID或用户ID | 邓刚&王默 | 2016-09-14 | 用户存储津贴设置时候，将其所选部门或员工（多个）存入数据库，此字段来自于前台用户操作，选择的津贴适用部分
	 */
	public void setDepartmentOrUserId(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>oa_salary.t_allowance_adapted.department_or_user_id</code>. 部门ID或用户ID | 邓刚&王默 | 2016-09-14 | 用户存储津贴设置时候，将其所选部门或员工（多个）存入数据库，此字段来自于前台用户操作，选择的津贴适用部分
	 */
	public java.lang.Long getDepartmentOrUserId() {
		return (java.lang.Long) getValue(4);
	}

	/**
	 * Setter for <code>oa_salary.t_allowance_adapted.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>oa_salary.t_allowance_adapted.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>oa_salary.t_allowance_adapted.update_time</code>.
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>oa_salary.t_allowance_adapted.update_time</code>.
	 */
	public java.sql.Timestamp getUpdateTime() {
		return (java.sql.Timestamp) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<org.jooq.types.UInteger, java.lang.Long, org.jooq.types.UInteger, org.jooq.types.UByte, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<org.jooq.types.UInteger, java.lang.Long, org.jooq.types.UInteger, org.jooq.types.UByte, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return jooq.model.tables.TAllowanceAdapted.T_ALLOWANCE_ADAPTED.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return jooq.model.tables.TAllowanceAdapted.T_ALLOWANCE_ADAPTED.TENANT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field3() {
		return jooq.model.tables.TAllowanceAdapted.T_ALLOWANCE_ADAPTED.ALLOWANCE_PLAN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field4() {
		return jooq.model.tables.TAllowanceAdapted.T_ALLOWANCE_ADAPTED.IS_ADAPT_TO_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return jooq.model.tables.TAllowanceAdapted.T_ALLOWANCE_ADAPTED.DEPARTMENT_OR_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return jooq.model.tables.TAllowanceAdapted.T_ALLOWANCE_ADAPTED.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return jooq.model.tables.TAllowanceAdapted.T_ALLOWANCE_ADAPTED.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getTenantId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value3() {
		return getAllowancePlanId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value4() {
		return getIsAdaptToUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getDepartmentOrUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TAllowanceAdaptedRecord value1(org.jooq.types.UInteger value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TAllowanceAdaptedRecord value2(java.lang.Long value) {
		setTenantId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TAllowanceAdaptedRecord value3(org.jooq.types.UInteger value) {
		setAllowancePlanId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TAllowanceAdaptedRecord value4(org.jooq.types.UByte value) {
		setIsAdaptToUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TAllowanceAdaptedRecord value5(java.lang.Long value) {
		setDepartmentOrUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TAllowanceAdaptedRecord value6(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TAllowanceAdaptedRecord value7(java.sql.Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TAllowanceAdaptedRecord values(org.jooq.types.UInteger value1, java.lang.Long value2, org.jooq.types.UInteger value3, org.jooq.types.UByte value4, java.lang.Long value5, java.sql.Timestamp value6, java.sql.Timestamp value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TAllowanceAdaptedRecord
	 */
	public TAllowanceAdaptedRecord() {
		super(jooq.model.tables.TAllowanceAdapted.T_ALLOWANCE_ADAPTED);
	}

	/**
	 * Create a detached, initialised TAllowanceAdaptedRecord
	 */
	public TAllowanceAdaptedRecord(org.jooq.types.UInteger id, java.lang.Long tenantId, org.jooq.types.UInteger allowancePlanId, org.jooq.types.UByte isAdaptToUser, java.lang.Long departmentOrUserId, java.sql.Timestamp createTime, java.sql.Timestamp updateTime) {
		super(jooq.model.tables.TAllowanceAdapted.T_ALLOWANCE_ADAPTED);

		setValue(0, id);
		setValue(1, tenantId);
		setValue(2, allowancePlanId);
		setValue(3, isAdaptToUser);
		setValue(4, departmentOrUserId);
		setValue(5, createTime);
		setValue(6, updateTime);
	}
}
