/**
 * This class is generated by jOOQ
 */
package jooq.model.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 基础工资表，包括调薪历史 | 邓刚&王默 | 2016-09-14 | 调薪页面，用户界面操作，输入
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBasicSalaryRecord extends org.jooq.impl.UpdatableRecordImpl<jooq.model.tables.records.TBasicSalaryRecord> implements org.jooq.Record8<org.jooq.types.ULong, java.lang.Long, java.lang.Long, org.jooq.types.ULong, org.jooq.types.ULong, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 148819152;

	/**
	 * Setter for <code>oa_salary.t_basic_salary.id</code>.
	 */
	public void setId(org.jooq.types.ULong value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>oa_salary.t_basic_salary.id</code>.
	 */
	public org.jooq.types.ULong getId() {
		return (org.jooq.types.ULong) getValue(0);
	}

	/**
	 * Setter for <code>oa_salary.t_basic_salary.tenant_id</code>. 公司ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public void setTenantId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>oa_salary.t_basic_salary.tenant_id</code>. 公司ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public java.lang.Long getTenantId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>oa_salary.t_basic_salary.user_id</code>. 用户ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public void setUserId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>oa_salary.t_basic_salary.user_id</code>. 用户ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>oa_salary.t_basic_salary.basic_salary_adjustment_id</code>. 调薪记录ID | 邓刚&王默 | 2016-09-13 | t_basic_salary_adjustment.id
	 */
	public void setBasicSalaryAdjustmentId(org.jooq.types.ULong value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>oa_salary.t_basic_salary.basic_salary_adjustment_id</code>. 调薪记录ID | 邓刚&王默 | 2016-09-13 | t_basic_salary_adjustment.id
	 */
	public org.jooq.types.ULong getBasicSalaryAdjustmentId() {
		return (org.jooq.types.ULong) getValue(3);
	}

	/**
	 * Setter for <code>oa_salary.t_basic_salary.basic_salary_type_id</code>. 对应基本工资项的ID | 邓刚&王默 | 2016-09-13 | t_basic_salary_type.id
	 */
	public void setBasicSalaryTypeId(org.jooq.types.ULong value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>oa_salary.t_basic_salary.basic_salary_type_id</code>. 对应基本工资项的ID | 邓刚&王默 | 2016-09-13 | t_basic_salary_type.id
	 */
	public org.jooq.types.ULong getBasicSalaryTypeId() {
		return (org.jooq.types.ULong) getValue(4);
	}

	/**
	 * Setter for <code>oa_salary.t_basic_salary.how_much</code>. 该基础工资项的金额 | 邓刚&王默 | 2016-09-13 | 用户界面操作，输入
	 */
	public void setHowMuch(java.lang.Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>oa_salary.t_basic_salary.how_much</code>. 该基础工资项的金额 | 邓刚&王默 | 2016-09-13 | 用户界面操作，输入
	 */
	public java.lang.Long getHowMuch() {
		return (java.lang.Long) getValue(5);
	}

	/**
	 * Setter for <code>oa_salary.t_basic_salary.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>oa_salary.t_basic_salary.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>oa_salary.t_basic_salary.update_time</code>.
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>oa_salary.t_basic_salary.update_time</code>.
	 */
	public java.sql.Timestamp getUpdateTime() {
		return (java.sql.Timestamp) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.ULong> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<org.jooq.types.ULong, java.lang.Long, java.lang.Long, org.jooq.types.ULong, org.jooq.types.ULong, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<org.jooq.types.ULong, java.lang.Long, java.lang.Long, org.jooq.types.ULong, org.jooq.types.ULong, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.ULong> field1() {
		return jooq.model.tables.TBasicSalary.T_BASIC_SALARY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return jooq.model.tables.TBasicSalary.T_BASIC_SALARY.TENANT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return jooq.model.tables.TBasicSalary.T_BASIC_SALARY.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.ULong> field4() {
		return jooq.model.tables.TBasicSalary.T_BASIC_SALARY.BASIC_SALARY_ADJUSTMENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.ULong> field5() {
		return jooq.model.tables.TBasicSalary.T_BASIC_SALARY.BASIC_SALARY_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field6() {
		return jooq.model.tables.TBasicSalary.T_BASIC_SALARY.HOW_MUCH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return jooq.model.tables.TBasicSalary.T_BASIC_SALARY.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return jooq.model.tables.TBasicSalary.T_BASIC_SALARY.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.ULong value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getTenantId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.ULong value4() {
		return getBasicSalaryAdjustmentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.ULong value5() {
		return getBasicSalaryTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value6() {
		return getHowMuch();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBasicSalaryRecord value1(org.jooq.types.ULong value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBasicSalaryRecord value2(java.lang.Long value) {
		setTenantId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBasicSalaryRecord value3(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBasicSalaryRecord value4(org.jooq.types.ULong value) {
		setBasicSalaryAdjustmentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBasicSalaryRecord value5(org.jooq.types.ULong value) {
		setBasicSalaryTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBasicSalaryRecord value6(java.lang.Long value) {
		setHowMuch(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBasicSalaryRecord value7(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBasicSalaryRecord value8(java.sql.Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBasicSalaryRecord values(org.jooq.types.ULong value1, java.lang.Long value2, java.lang.Long value3, org.jooq.types.ULong value4, org.jooq.types.ULong value5, java.lang.Long value6, java.sql.Timestamp value7, java.sql.Timestamp value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TBasicSalaryRecord
	 */
	public TBasicSalaryRecord() {
		super(jooq.model.tables.TBasicSalary.T_BASIC_SALARY);
	}

	/**
	 * Create a detached, initialised TBasicSalaryRecord
	 */
	public TBasicSalaryRecord(org.jooq.types.ULong id, java.lang.Long tenantId, java.lang.Long userId, org.jooq.types.ULong basicSalaryAdjustmentId, org.jooq.types.ULong basicSalaryTypeId, java.lang.Long howMuch, java.sql.Timestamp createTime, java.sql.Timestamp updateTime) {
		super(jooq.model.tables.TBasicSalary.T_BASIC_SALARY);

		setValue(0, id);
		setValue(1, tenantId);
		setValue(2, userId);
		setValue(3, basicSalaryAdjustmentId);
		setValue(4, basicSalaryTypeId);
		setValue(5, howMuch);
		setValue(6, createTime);
		setValue(7, updateTime);
	}
}
