/**
 * This class is generated by jOOQ
 */
package jooq.model.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 存储调薪记录 | 邓刚&王默 | 2016-09-14 | 调薪页面，用户界面操作
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBasicSalaryAdjustmentRecord extends org.jooq.impl.UpdatableRecordImpl<jooq.model.tables.records.TBasicSalaryAdjustmentRecord> implements org.jooq.Record6<org.jooq.types.ULong, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.String, java.sql.Timestamp> {

	private static final long serialVersionUID = -383767401;

	/**
	 * Setter for <code>oa_salary.t_basic_salary_adjustment.id</code>.
	 */
	public void setId(org.jooq.types.ULong value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>oa_salary.t_basic_salary_adjustment.id</code>.
	 */
	public org.jooq.types.ULong getId() {
		return (org.jooq.types.ULong) getValue(0);
	}

	/**
	 * Setter for <code>oa_salary.t_basic_salary_adjustment.tenant_id</code>. 公司ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public void setTenantId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>oa_salary.t_basic_salary_adjustment.tenant_id</code>. 公司ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public java.lang.Long getTenantId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>oa_salary.t_basic_salary_adjustment.user_id</code>. 用户ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public void setUserId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>oa_salary.t_basic_salary_adjustment.user_id</code>. 用户ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>oa_salary.t_basic_salary_adjustment.taking_effect_time</code>. 调薪生效时间 (default 0 -立即生效) | 邓刚&王默 | 2016-09-14 | 用户界面操作，时间选择控件
	 */
	public void setTakingEffectTime(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>oa_salary.t_basic_salary_adjustment.taking_effect_time</code>. 调薪生效时间 (default 0 -立即生效) | 邓刚&王默 | 2016-09-14 | 用户界面操作，时间选择控件
	 */
	public java.lang.Integer getTakingEffectTime() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>oa_salary.t_basic_salary_adjustment.salary_adjustment_reason</code>. 调薪原因 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public void setSalaryAdjustmentReason(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>oa_salary.t_basic_salary_adjustment.salary_adjustment_reason</code>. 调薪原因 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public java.lang.String getSalaryAdjustmentReason() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>oa_salary.t_basic_salary_adjustment.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>oa_salary.t_basic_salary_adjustment.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.ULong> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<org.jooq.types.ULong, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.String, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<org.jooq.types.ULong, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.String, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.ULong> field1() {
		return jooq.model.tables.TBasicSalaryAdjustment.T_BASIC_SALARY_ADJUSTMENT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return jooq.model.tables.TBasicSalaryAdjustment.T_BASIC_SALARY_ADJUSTMENT.TENANT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return jooq.model.tables.TBasicSalaryAdjustment.T_BASIC_SALARY_ADJUSTMENT.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return jooq.model.tables.TBasicSalaryAdjustment.T_BASIC_SALARY_ADJUSTMENT.TAKING_EFFECT_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return jooq.model.tables.TBasicSalaryAdjustment.T_BASIC_SALARY_ADJUSTMENT.SALARY_ADJUSTMENT_REASON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return jooq.model.tables.TBasicSalaryAdjustment.T_BASIC_SALARY_ADJUSTMENT.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.ULong value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getTenantId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getTakingEffectTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getSalaryAdjustmentReason();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBasicSalaryAdjustmentRecord value1(org.jooq.types.ULong value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBasicSalaryAdjustmentRecord value2(java.lang.Long value) {
		setTenantId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBasicSalaryAdjustmentRecord value3(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBasicSalaryAdjustmentRecord value4(java.lang.Integer value) {
		setTakingEffectTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBasicSalaryAdjustmentRecord value5(java.lang.String value) {
		setSalaryAdjustmentReason(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBasicSalaryAdjustmentRecord value6(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBasicSalaryAdjustmentRecord values(org.jooq.types.ULong value1, java.lang.Long value2, java.lang.Long value3, java.lang.Integer value4, java.lang.String value5, java.sql.Timestamp value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TBasicSalaryAdjustmentRecord
	 */
	public TBasicSalaryAdjustmentRecord() {
		super(jooq.model.tables.TBasicSalaryAdjustment.T_BASIC_SALARY_ADJUSTMENT);
	}

	/**
	 * Create a detached, initialised TBasicSalaryAdjustmentRecord
	 */
	public TBasicSalaryAdjustmentRecord(org.jooq.types.ULong id, java.lang.Long tenantId, java.lang.Long userId, java.lang.Integer takingEffectTime, java.lang.String salaryAdjustmentReason, java.sql.Timestamp createTime) {
		super(jooq.model.tables.TBasicSalaryAdjustment.T_BASIC_SALARY_ADJUSTMENT);

		setValue(0, id);
		setValue(1, tenantId);
		setValue(2, userId);
		setValue(3, takingEffectTime);
		setValue(4, salaryAdjustmentReason);
		setValue(5, createTime);
	}
}
