/**
 * This class is generated by jOOQ
 */
package jooq.model.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 记录分摊计税使用 | 王默 | 2016-09-14 | 奖金设置页面，用户界面操作
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBonusApportionedRecord extends org.jooq.impl.UpdatableRecordImpl<jooq.model.tables.records.TBonusApportionedRecord> implements org.jooq.Record8<org.jooq.types.UInteger, java.lang.Long, java.lang.Short, org.jooq.types.UInteger, org.jooq.types.UByte, org.jooq.types.UByte, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = -88057173;

	/**
	 * Setter for <code>oa_salary.t_bonus_apportioned.id</code>.
	 */
	public void setId(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>oa_salary.t_bonus_apportioned.id</code>.
	 */
	public org.jooq.types.UInteger getId() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>oa_salary.t_bonus_apportioned.tenant_id</code>. 公司ID | 王默 | 2016-09-14 | 账号模块
	 */
	public void setTenantId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>oa_salary.t_bonus_apportioned.tenant_id</code>. 公司ID | 王默 | 2016-09-14 | 账号模块
	 */
	public java.lang.Long getTenantId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>oa_salary.t_bonus_apportioned.year</code>. 年份(每年，每个公司，只能有一种奖金) 王默 | 2016-09-14 | 后台逻辑生成
	 */
	public void setYear(java.lang.Short value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>oa_salary.t_bonus_apportioned.year</code>. 年份(每年，每个公司，只能有一种奖金) 王默 | 2016-09-14 | 后台逻辑生成
	 */
	public java.lang.Short getYear() {
		return (java.lang.Short) getValue(2);
	}

	/**
	 * Setter for <code>oa_salary.t_bonus_apportioned.bonus_type_id</code>. 存储分摊计税应用到了哪个奖金类型上 | 王默 | 2016-09-14 | t_bonus_type.id
	 */
	public void setBonusTypeId(org.jooq.types.UInteger value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>oa_salary.t_bonus_apportioned.bonus_type_id</code>. 存储分摊计税应用到了哪个奖金类型上 | 王默 | 2016-09-14 | t_bonus_type.id
	 */
	public org.jooq.types.UInteger getBonusTypeId() {
		return (org.jooq.types.UInteger) getValue(3);
	}

	/**
	 * Setter for <code>oa_salary.t_bonus_apportioned.is_used</code>. 该年份分摊计税是否已经被使用了 | 王默 | 2016-09-14 | @1:未用 @2:已用 | 用户界面操作，checkbox
	 */
	public void setIsUsed(org.jooq.types.UByte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>oa_salary.t_bonus_apportioned.is_used</code>. 该年份分摊计税是否已经被使用了 | 王默 | 2016-09-14 | @1:未用 @2:已用 | 用户界面操作，checkbox
	 */
	public org.jooq.types.UByte getIsUsed() {
		return (org.jooq.types.UByte) getValue(4);
	}

	/**
	 * Setter for <code>oa_salary.t_bonus_apportioned.used_month</code>. 哪个月使用的(默认值表示未被使用) | 王默 | 2016-09-14 | 后台逻辑生成
	 */
	public void setUsedMonth(org.jooq.types.UByte value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>oa_salary.t_bonus_apportioned.used_month</code>. 哪个月使用的(默认值表示未被使用) | 王默 | 2016-09-14 | 后台逻辑生成
	 */
	public org.jooq.types.UByte getUsedMonth() {
		return (org.jooq.types.UByte) getValue(5);
	}

	/**
	 * Setter for <code>oa_salary.t_bonus_apportioned.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>oa_salary.t_bonus_apportioned.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>oa_salary.t_bonus_apportioned.update_time</code>.
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>oa_salary.t_bonus_apportioned.update_time</code>.
	 */
	public java.sql.Timestamp getUpdateTime() {
		return (java.sql.Timestamp) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<org.jooq.types.UInteger, java.lang.Long, java.lang.Short, org.jooq.types.UInteger, org.jooq.types.UByte, org.jooq.types.UByte, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<org.jooq.types.UInteger, java.lang.Long, java.lang.Short, org.jooq.types.UInteger, org.jooq.types.UByte, org.jooq.types.UByte, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return jooq.model.tables.TBonusApportioned.T_BONUS_APPORTIONED.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return jooq.model.tables.TBonusApportioned.T_BONUS_APPORTIONED.TENANT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field3() {
		return jooq.model.tables.TBonusApportioned.T_BONUS_APPORTIONED.YEAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field4() {
		return jooq.model.tables.TBonusApportioned.T_BONUS_APPORTIONED.BONUS_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field5() {
		return jooq.model.tables.TBonusApportioned.T_BONUS_APPORTIONED.IS_USED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field6() {
		return jooq.model.tables.TBonusApportioned.T_BONUS_APPORTIONED.USED_MONTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return jooq.model.tables.TBonusApportioned.T_BONUS_APPORTIONED.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return jooq.model.tables.TBonusApportioned.T_BONUS_APPORTIONED.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getTenantId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value3() {
		return getYear();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value4() {
		return getBonusTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value5() {
		return getIsUsed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value6() {
		return getUsedMonth();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBonusApportionedRecord value1(org.jooq.types.UInteger value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBonusApportionedRecord value2(java.lang.Long value) {
		setTenantId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBonusApportionedRecord value3(java.lang.Short value) {
		setYear(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBonusApportionedRecord value4(org.jooq.types.UInteger value) {
		setBonusTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBonusApportionedRecord value5(org.jooq.types.UByte value) {
		setIsUsed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBonusApportionedRecord value6(org.jooq.types.UByte value) {
		setUsedMonth(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBonusApportionedRecord value7(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBonusApportionedRecord value8(java.sql.Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBonusApportionedRecord values(org.jooq.types.UInteger value1, java.lang.Long value2, java.lang.Short value3, org.jooq.types.UInteger value4, org.jooq.types.UByte value5, org.jooq.types.UByte value6, java.sql.Timestamp value7, java.sql.Timestamp value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TBonusApportionedRecord
	 */
	public TBonusApportionedRecord() {
		super(jooq.model.tables.TBonusApportioned.T_BONUS_APPORTIONED);
	}

	/**
	 * Create a detached, initialised TBonusApportionedRecord
	 */
	public TBonusApportionedRecord(org.jooq.types.UInteger id, java.lang.Long tenantId, java.lang.Short year, org.jooq.types.UInteger bonusTypeId, org.jooq.types.UByte isUsed, org.jooq.types.UByte usedMonth, java.sql.Timestamp createTime, java.sql.Timestamp updateTime) {
		super(jooq.model.tables.TBonusApportioned.T_BONUS_APPORTIONED);

		setValue(0, id);
		setValue(1, tenantId);
		setValue(2, year);
		setValue(3, bonusTypeId);
		setValue(4, isUsed);
		setValue(5, usedMonth);
		setValue(6, createTime);
		setValue(7, updateTime);
	}
}
