/**
 * This class is generated by jOOQ
 */
package jooq.model.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 存储归档历史 | 王默 | 2016-09-14 | 历史归档页面，用户界面操作
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TFilingHistoryRecord extends org.jooq.impl.UpdatableRecordImpl<jooq.model.tables.records.TFilingHistoryRecord> implements org.jooq.Record6<org.jooq.types.ULong, java.lang.Long, java.lang.Integer, org.jooq.types.UByte, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 1759366670;

	/**
	 * Setter for <code>oa_salary.t_filing_history.id</code>.
	 */
	public void setId(org.jooq.types.ULong value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>oa_salary.t_filing_history.id</code>.
	 */
	public org.jooq.types.ULong getId() {
		return (org.jooq.types.ULong) getValue(0);
	}

	/**
	 * Setter for <code>oa_salary.t_filing_history.tenant_id</code>. 公司ID | 王默 | 2016-09-14 | 账号模块
	 */
	public void setTenantId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>oa_salary.t_filing_history.tenant_id</code>. 公司ID | 王默 | 2016-09-14 | 账号模块
	 */
	public java.lang.Long getTenantId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>oa_salary.t_filing_history.filing_time</code>. 归档的月份 | 王默 | 2016-09-14 | 用户界面操作
	 */
	public void setFilingTime(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>oa_salary.t_filing_history.filing_time</code>. 归档的月份 | 王默 | 2016-09-14 | 用户界面操作
	 */
	public java.lang.Integer getFilingTime() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>oa_salary.t_filing_history.filing_state</code>. 归档状态 | 王默 | 2016-09-14 | @0:未归档 @1:已归档 @2:已封帐 | 归档行为
	 */
	public void setFilingState(org.jooq.types.UByte value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>oa_salary.t_filing_history.filing_state</code>. 归档状态 | 王默 | 2016-09-14 | @0:未归档 @1:已归档 @2:已封帐 | 归档行为
	 */
	public org.jooq.types.UByte getFilingState() {
		return (org.jooq.types.UByte) getValue(3);
	}

	/**
	 * Setter for <code>oa_salary.t_filing_history.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>oa_salary.t_filing_history.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>oa_salary.t_filing_history.update_time</code>.
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>oa_salary.t_filing_history.update_time</code>.
	 */
	public java.sql.Timestamp getUpdateTime() {
		return (java.sql.Timestamp) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.ULong> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<org.jooq.types.ULong, java.lang.Long, java.lang.Integer, org.jooq.types.UByte, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<org.jooq.types.ULong, java.lang.Long, java.lang.Integer, org.jooq.types.UByte, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.ULong> field1() {
		return jooq.model.tables.TFilingHistory.T_FILING_HISTORY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return jooq.model.tables.TFilingHistory.T_FILING_HISTORY.TENANT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return jooq.model.tables.TFilingHistory.T_FILING_HISTORY.FILING_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field4() {
		return jooq.model.tables.TFilingHistory.T_FILING_HISTORY.FILING_STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return jooq.model.tables.TFilingHistory.T_FILING_HISTORY.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return jooq.model.tables.TFilingHistory.T_FILING_HISTORY.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.ULong value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getTenantId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getFilingTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value4() {
		return getFilingState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TFilingHistoryRecord value1(org.jooq.types.ULong value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TFilingHistoryRecord value2(java.lang.Long value) {
		setTenantId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TFilingHistoryRecord value3(java.lang.Integer value) {
		setFilingTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TFilingHistoryRecord value4(org.jooq.types.UByte value) {
		setFilingState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TFilingHistoryRecord value5(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TFilingHistoryRecord value6(java.sql.Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TFilingHistoryRecord values(org.jooq.types.ULong value1, java.lang.Long value2, java.lang.Integer value3, org.jooq.types.UByte value4, java.sql.Timestamp value5, java.sql.Timestamp value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TFilingHistoryRecord
	 */
	public TFilingHistoryRecord() {
		super(jooq.model.tables.TFilingHistory.T_FILING_HISTORY);
	}

	/**
	 * Create a detached, initialised TFilingHistoryRecord
	 */
	public TFilingHistoryRecord(org.jooq.types.ULong id, java.lang.Long tenantId, java.lang.Integer filingTime, org.jooq.types.UByte filingState, java.sql.Timestamp createTime, java.sql.Timestamp updateTime) {
		super(jooq.model.tables.TFilingHistory.T_FILING_HISTORY);

		setValue(0, id);
		setValue(1, tenantId);
		setValue(2, filingTime);
		setValue(3, filingState);
		setValue(4, createTime);
		setValue(5, updateTime);
	}
}
