/**
 * This class is generated by jOOQ
 */
package jooq.model.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 存储归档历史 | 邓刚&王默 | 2016-09-14 | 历史归档页面，用户界面操作
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TInsuranceFilingHistoryRecord extends org.jooq.impl.UpdatableRecordImpl<jooq.model.tables.records.TInsuranceFilingHistoryRecord> implements org.jooq.Record5<org.jooq.types.ULong, java.lang.Integer, org.jooq.types.UByte, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 810857006;

	/**
	 * Setter for <code>oa_salary.t_insurance_filing_history.tenant_id</code>. 公司ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public void setTenantId(org.jooq.types.ULong value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurance_filing_history.tenant_id</code>. 公司ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public org.jooq.types.ULong getTenantId() {
		return (org.jooq.types.ULong) getValue(0);
	}

	/**
	 * Setter for <code>oa_salary.t_insurance_filing_history.current</code>.
	 */
	public void setCurrent(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurance_filing_history.current</code>.
	 */
	public java.lang.Integer getCurrent() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>oa_salary.t_insurance_filing_history.filing_state</code>. 归档状态 | 邓刚&王默 | 2016-09-14 | @0:未归档 @1:社保已归档 @2公积金已归档 @3:已封帐 | 归档行为
	 */
	public void setFilingState(org.jooq.types.UByte value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurance_filing_history.filing_state</code>. 归档状态 | 邓刚&王默 | 2016-09-14 | @0:未归档 @1:社保已归档 @2公积金已归档 @3:已封帐 | 归档行为
	 */
	public org.jooq.types.UByte getFilingState() {
		return (org.jooq.types.UByte) getValue(2);
	}

	/**
	 * Setter for <code>oa_salary.t_insurance_filing_history.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurance_filing_history.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>oa_salary.t_insurance_filing_history.update_time</code>.
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurance_filing_history.update_time</code>.
	 */
	public java.sql.Timestamp getUpdateTime() {
		return (java.sql.Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.ULong> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<org.jooq.types.ULong, java.lang.Integer, org.jooq.types.UByte, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<org.jooq.types.ULong, java.lang.Integer, org.jooq.types.UByte, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.ULong> field1() {
		return jooq.model.tables.TInsuranceFilingHistory.T_INSURANCE_FILING_HISTORY.TENANT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return jooq.model.tables.TInsuranceFilingHistory.T_INSURANCE_FILING_HISTORY.CURRENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field3() {
		return jooq.model.tables.TInsuranceFilingHistory.T_INSURANCE_FILING_HISTORY.FILING_STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return jooq.model.tables.TInsuranceFilingHistory.T_INSURANCE_FILING_HISTORY.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return jooq.model.tables.TInsuranceFilingHistory.T_INSURANCE_FILING_HISTORY.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.ULong value1() {
		return getTenantId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getCurrent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value3() {
		return getFilingState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsuranceFilingHistoryRecord value1(org.jooq.types.ULong value) {
		setTenantId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsuranceFilingHistoryRecord value2(java.lang.Integer value) {
		setCurrent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsuranceFilingHistoryRecord value3(org.jooq.types.UByte value) {
		setFilingState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsuranceFilingHistoryRecord value4(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsuranceFilingHistoryRecord value5(java.sql.Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsuranceFilingHistoryRecord values(org.jooq.types.ULong value1, java.lang.Integer value2, org.jooq.types.UByte value3, java.sql.Timestamp value4, java.sql.Timestamp value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TInsuranceFilingHistoryRecord
	 */
	public TInsuranceFilingHistoryRecord() {
		super(jooq.model.tables.TInsuranceFilingHistory.T_INSURANCE_FILING_HISTORY);
	}

	/**
	 * Create a detached, initialised TInsuranceFilingHistoryRecord
	 */
	public TInsuranceFilingHistoryRecord(org.jooq.types.ULong tenantId, java.lang.Integer current, org.jooq.types.UByte filingState, java.sql.Timestamp createTime, java.sql.Timestamp updateTime) {
		super(jooq.model.tables.TInsuranceFilingHistory.T_INSURANCE_FILING_HISTORY);

		setValue(0, tenantId);
		setValue(1, current);
		setValue(2, filingState);
		setValue(3, createTime);
		setValue(4, updateTime);
	}
}
