/**
 * This class is generated by jOOQ
 */
package jooq.model.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 保险公积金配置 | 邓刚&王默 | 2016-09-14 | 社保详情页面，用户界面操作
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TInsurancesHousefundConfigRecord extends org.jooq.impl.UpdatableRecordImpl<jooq.model.tables.records.TInsurancesHousefundConfigRecord> implements org.jooq.Record16<org.jooq.types.ULong, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = -293742830;

	/**
	 * Setter for <code>oa_salary.t_insurances_housefund_config.id</code>.
	 */
	public void setId(org.jooq.types.ULong value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurances_housefund_config.id</code>.
	 */
	public org.jooq.types.ULong getId() {
		return (org.jooq.types.ULong) getValue(0);
	}

	/**
	 * Setter for <code>oa_salary.t_insurances_housefund_config.tenant_id</code>. 公司ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public void setTenantId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurances_housefund_config.tenant_id</code>. 公司ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public java.lang.Long getTenantId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>oa_salary.t_insurances_housefund_config.user_id</code>. 用户ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public void setUserId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurances_housefund_config.user_id</code>. 用户ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>oa_salary.t_insurances_housefund_config.insurances_plan_id</code>. 社保参保城市id | 邓刚&王默 | 2016-09-14 | t_location.id
	 */
	public void setInsurancesPlanId(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurances_housefund_config.insurances_plan_id</code>. 社保参保城市id | 邓刚&王默 | 2016-09-14 | t_location.id
	 */
	public java.lang.Long getInsurancesPlanId() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>oa_salary.t_insurances_housefund_config.housefund_plan_id</code>. 公积金城市id | 邓刚&王默 | 2016-09-14 | t_location.id
	 */
	public void setHousefundPlanId(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurances_housefund_config.housefund_plan_id</code>. 公积金城市id | 邓刚&王默 | 2016-09-14 | t_location.id
	 */
	public java.lang.Long getHousefundPlanId() {
		return (java.lang.Long) getValue(4);
	}

	/**
	 * Setter for <code>oa_salary.t_insurances_housefund_config.insurances_basefee</code>. 社保基数 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public void setInsurancesBasefee(java.lang.Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurances_housefund_config.insurances_basefee</code>. 社保基数 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public java.lang.Long getInsurancesBasefee() {
		return (java.lang.Long) getValue(5);
	}

	/**
	 * Setter for <code>oa_salary.t_insurances_housefund_config.housefund_basefee</code>. 公积金基数 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public void setHousefundBasefee(java.lang.Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurances_housefund_config.housefund_basefee</code>. 公积金基数 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public java.lang.Long getHousefundBasefee() {
		return (java.lang.Long) getValue(6);
	}

	/**
	 * Setter for <code>oa_salary.t_insurances_housefund_config.industrial_injury_proportion</code>. 工伤保险比例 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public void setIndustrialInjuryProportion(java.lang.Long value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurances_housefund_config.industrial_injury_proportion</code>. 工伤保险比例 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public java.lang.Long getIndustrialInjuryProportion() {
		return (java.lang.Long) getValue(7);
	}

	/**
	 * Setter for <code>oa_salary.t_insurances_housefund_config.company_housefund_proportion</code>. 公司公积金缴纳比例 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public void setCompanyHousefundProportion(java.lang.Long value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurances_housefund_config.company_housefund_proportion</code>. 公司公积金缴纳比例 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public java.lang.Long getCompanyHousefundProportion() {
		return (java.lang.Long) getValue(8);
	}

	/**
	 * Setter for <code>oa_salary.t_insurances_housefund_config.employee_housefund_proportion</code>. 个人公积金缴纳比例 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public void setEmployeeHousefundProportion(java.lang.Long value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurances_housefund_config.employee_housefund_proportion</code>. 个人公积金缴纳比例 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public java.lang.Long getEmployeeHousefundProportion() {
		return (java.lang.Long) getValue(9);
	}

	/**
	 * Setter for <code>oa_salary.t_insurances_housefund_config.no_insurance</code>. 社保缴纳开始月 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public void setNoInsurance(java.lang.Byte value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurances_housefund_config.no_insurance</code>. 社保缴纳开始月 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public java.lang.Byte getNoInsurance() {
		return (java.lang.Byte) getValue(10);
	}

	/**
	 * Setter for <code>oa_salary.t_insurances_housefund_config.no_housefund</code>. 公积金缴纳开始月 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public void setNoHousefund(java.lang.Byte value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurances_housefund_config.no_housefund</code>. 公积金缴纳开始月 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public java.lang.Byte getNoHousefund() {
		return (java.lang.Byte) getValue(11);
	}

	/**
	 * Setter for <code>oa_salary.t_insurances_housefund_config.insurances_pay_type</code>. 社保缴纳方式 | 邓刚&王默 | 2016-09-14 | @1:正常 @2:全部个人缴纳 @3:全部公司缴纳 @4:不缴纳 | 用户界面操作，选择
	 */
	public void setInsurancesPayType(java.lang.Byte value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurances_housefund_config.insurances_pay_type</code>. 社保缴纳方式 | 邓刚&王默 | 2016-09-14 | @1:正常 @2:全部个人缴纳 @3:全部公司缴纳 @4:不缴纳 | 用户界面操作，选择
	 */
	public java.lang.Byte getInsurancesPayType() {
		return (java.lang.Byte) getValue(12);
	}

	/**
	 * Setter for <code>oa_salary.t_insurances_housefund_config.housefund_pay_type</code>. 公积金缴纳方式 | 邓刚&王默 | 2016-09-14 | @1:正常 @2:全部个人缴纳 @3:全部公司缴纳 @4:不缴纳 | 用户界面操作，选择
	 */
	public void setHousefundPayType(java.lang.Byte value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurances_housefund_config.housefund_pay_type</code>. 公积金缴纳方式 | 邓刚&王默 | 2016-09-14 | @1:正常 @2:全部个人缴纳 @3:全部公司缴纳 @4:不缴纳 | 用户界面操作，选择
	 */
	public java.lang.Byte getHousefundPayType() {
		return (java.lang.Byte) getValue(13);
	}

	/**
	 * Setter for <code>oa_salary.t_insurances_housefund_config.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurances_housefund_config.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(14);
	}

	/**
	 * Setter for <code>oa_salary.t_insurances_housefund_config.update_time</code>.
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>oa_salary.t_insurances_housefund_config.update_time</code>.
	 */
	public java.sql.Timestamp getUpdateTime() {
		return (java.sql.Timestamp) getValue(15);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.ULong> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record16 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row16<org.jooq.types.ULong, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row16) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row16<org.jooq.types.ULong, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row16) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.ULong> field1() {
		return jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG.TENANT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG.INSURANCES_PLAN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG.HOUSEFUND_PLAN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field6() {
		return jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG.INSURANCES_BASEFEE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field7() {
		return jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG.HOUSEFUND_BASEFEE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field8() {
		return jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG.INDUSTRIAL_INJURY_PROPORTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field9() {
		return jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG.COMPANY_HOUSEFUND_PROPORTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field10() {
		return jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG.EMPLOYEE_HOUSEFUND_PROPORTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field11() {
		return jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG.NO_INSURANCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field12() {
		return jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG.NO_HOUSEFUND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field13() {
		return jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG.INSURANCES_PAY_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field14() {
		return jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG.HOUSEFUND_PAY_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field15() {
		return jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field16() {
		return jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.ULong value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getTenantId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getInsurancesPlanId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getHousefundPlanId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value6() {
		return getInsurancesBasefee();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value7() {
		return getHousefundBasefee();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value8() {
		return getIndustrialInjuryProportion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value9() {
		return getCompanyHousefundProportion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value10() {
		return getEmployeeHousefundProportion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value11() {
		return getNoInsurance();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value12() {
		return getNoHousefund();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value13() {
		return getInsurancesPayType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value14() {
		return getHousefundPayType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value15() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value16() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsurancesHousefundConfigRecord value1(org.jooq.types.ULong value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsurancesHousefundConfigRecord value2(java.lang.Long value) {
		setTenantId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsurancesHousefundConfigRecord value3(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsurancesHousefundConfigRecord value4(java.lang.Long value) {
		setInsurancesPlanId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsurancesHousefundConfigRecord value5(java.lang.Long value) {
		setHousefundPlanId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsurancesHousefundConfigRecord value6(java.lang.Long value) {
		setInsurancesBasefee(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsurancesHousefundConfigRecord value7(java.lang.Long value) {
		setHousefundBasefee(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsurancesHousefundConfigRecord value8(java.lang.Long value) {
		setIndustrialInjuryProportion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsurancesHousefundConfigRecord value9(java.lang.Long value) {
		setCompanyHousefundProportion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsurancesHousefundConfigRecord value10(java.lang.Long value) {
		setEmployeeHousefundProportion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsurancesHousefundConfigRecord value11(java.lang.Byte value) {
		setNoInsurance(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsurancesHousefundConfigRecord value12(java.lang.Byte value) {
		setNoHousefund(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsurancesHousefundConfigRecord value13(java.lang.Byte value) {
		setInsurancesPayType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsurancesHousefundConfigRecord value14(java.lang.Byte value) {
		setHousefundPayType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsurancesHousefundConfigRecord value15(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsurancesHousefundConfigRecord value16(java.sql.Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInsurancesHousefundConfigRecord values(org.jooq.types.ULong value1, java.lang.Long value2, java.lang.Long value3, java.lang.Long value4, java.lang.Long value5, java.lang.Long value6, java.lang.Long value7, java.lang.Long value8, java.lang.Long value9, java.lang.Long value10, java.lang.Byte value11, java.lang.Byte value12, java.lang.Byte value13, java.lang.Byte value14, java.sql.Timestamp value15, java.sql.Timestamp value16) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TInsurancesHousefundConfigRecord
	 */
	public TInsurancesHousefundConfigRecord() {
		super(jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG);
	}

	/**
	 * Create a detached, initialised TInsurancesHousefundConfigRecord
	 */
	public TInsurancesHousefundConfigRecord(org.jooq.types.ULong id, java.lang.Long tenantId, java.lang.Long userId, java.lang.Long insurancesPlanId, java.lang.Long housefundPlanId, java.lang.Long insurancesBasefee, java.lang.Long housefundBasefee, java.lang.Long industrialInjuryProportion, java.lang.Long companyHousefundProportion, java.lang.Long employeeHousefundProportion, java.lang.Byte noInsurance, java.lang.Byte noHousefund, java.lang.Byte insurancesPayType, java.lang.Byte housefundPayType, java.sql.Timestamp createTime, java.sql.Timestamp updateTime) {
		super(jooq.model.tables.TInsurancesHousefundConfig.T_INSURANCES_HOUSEFUND_CONFIG);

		setValue(0, id);
		setValue(1, tenantId);
		setValue(2, userId);
		setValue(3, insurancesPlanId);
		setValue(4, housefundPlanId);
		setValue(5, insurancesBasefee);
		setValue(6, housefundBasefee);
		setValue(7, industrialInjuryProportion);
		setValue(8, companyHousefundProportion);
		setValue(9, employeeHousefundProportion);
		setValue(10, noInsurance);
		setValue(11, noHousefund);
		setValue(12, insurancesPayType);
		setValue(13, housefundPayType);
		setValue(14, createTime);
		setValue(15, updateTime);
	}
}
