/**
 * This class is generated by jOOQ
 */
package jooq.model.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 记录位置和该位置社保公积金数据 | 王默 | 2016-09-14 | 后台系统管理员输入
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TLocationRecord extends org.jooq.impl.UpdatableRecordImpl<jooq.model.tables.records.TLocationRecord> implements org.jooq.Record22<org.jooq.types.UInteger, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = -1220937282;

	/**
	 * Setter for <code>oa_salary.t_location.id</code>.
	 */
	public void setId(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.id</code>.
	 */
	public org.jooq.types.UInteger getId() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>oa_salary.t_location.province</code>. 省级行政单位  | 王默 | 2016-09-14 | 
	 */
	public void setProvince(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.province</code>. 省级行政单位  | 王默 | 2016-09-14 | 
	 */
	public java.lang.String getProvince() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>oa_salary.t_location.city</code>. 市级行政单位 | 王默 | 2016-09-14 | 
	 */
	public void setCity(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.city</code>. 市级行政单位 | 王默 | 2016-09-14 | 
	 */
	public java.lang.String getCity() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>oa_salary.t_location.county</code>. 县级行政单位 | 王默 | 2016-09-14 | 
	 */
	public void setCounty(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.county</code>. 县级行政单位 | 王默 | 2016-09-14 | 
	 */
	public java.lang.String getCounty() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>oa_salary.t_location.company_endowment</code>. 公司养老保险缴纳比例 | 王默 | 2016-09-14 | 
	 */
	public void setCompanyEndowment(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.company_endowment</code>. 公司养老保险缴纳比例 | 王默 | 2016-09-14 | 
	 */
	public java.lang.Integer getCompanyEndowment() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>oa_salary.t_location.company_medical</code>. 公司医疗险缴纳比例 | 王默 | 2016-09-14 | 
	 */
	public void setCompanyMedical(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.company_medical</code>. 公司医疗险缴纳比例 | 王默 | 2016-09-14 | 
	 */
	public java.lang.Integer getCompanyMedical() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>oa_salary.t_location.company_unemployment</code>. 公司失业险缴纳比例 | 王默 | 2016-09-14 | 
	 */
	public void setCompanyUnemployment(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.company_unemployment</code>. 公司失业险缴纳比例 | 王默 | 2016-09-14 | 
	 */
	public java.lang.Integer getCompanyUnemployment() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>oa_salary.t_location.company_maternity</code>. 公司生育险缴纳比例 | 王默 | 2016-09-14 | 
	 */
	public void setCompanyMaternity(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.company_maternity</code>. 公司生育险缴纳比例 | 王默 | 2016-09-14 | 
	 */
	public java.lang.Integer getCompanyMaternity() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>oa_salary.t_location.company_housefund</code>. 公司住房公积金缴纳比例 | 王默 | 2016-09-14 | 
	 */
	public void setCompanyHousefund(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.company_housefund</code>. 公司住房公积金缴纳比例 | 王默 | 2016-09-14 | 
	 */
	public java.lang.Integer getCompanyHousefund() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>oa_salary.t_location.industrial_injury_start</code>. 此地区工伤保险的起始值 | 王默 | 2016-09-14 | 
	 */
	public void setIndustrialInjuryStart(java.lang.Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.industrial_injury_start</code>. 此地区工伤保险的起始值 | 王默 | 2016-09-14 | 
	 */
	public java.lang.Integer getIndustrialInjuryStart() {
		return (java.lang.Integer) getValue(9);
	}

	/**
	 * Setter for <code>oa_salary.t_location.industrial_jnjury_end</code>. 此地区工伤险最高值 | 王默 | 2016-09-14 | 
	 */
	public void setIndustrialJnjuryEnd(java.lang.Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.industrial_jnjury_end</code>. 此地区工伤险最高值 | 王默 | 2016-09-14 | 
	 */
	public java.lang.Integer getIndustrialJnjuryEnd() {
		return (java.lang.Integer) getValue(10);
	}

	/**
	 * Setter for <code>oa_salary.t_location.industrial_injury_recommended</code>. 此地区工伤保险的建议值 | 王默 | 2016-09-14 | 
	 */
	public void setIndustrialInjuryRecommended(java.lang.Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.industrial_injury_recommended</code>. 此地区工伤保险的建议值 | 王默 | 2016-09-14 | 
	 */
	public java.lang.Integer getIndustrialInjuryRecommended() {
		return (java.lang.Integer) getValue(11);
	}

	/**
	 * Setter for <code>oa_salary.t_location.employee_endowment</code>. 员工缴纳养老保险比例 | 王默 | 2016-09-14 | 
	 */
	public void setEmployeeEndowment(java.lang.Integer value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.employee_endowment</code>. 员工缴纳养老保险比例 | 王默 | 2016-09-14 | 
	 */
	public java.lang.Integer getEmployeeEndowment() {
		return (java.lang.Integer) getValue(12);
	}

	/**
	 * Setter for <code>oa_salary.t_location.employee_medical</code>. 员工缴纳医疗险比例 | 王默 | 2016-09-14 | 
	 */
	public void setEmployeeMedical(java.lang.Integer value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.employee_medical</code>. 员工缴纳医疗险比例 | 王默 | 2016-09-14 | 
	 */
	public java.lang.Integer getEmployeeMedical() {
		return (java.lang.Integer) getValue(13);
	}

	/**
	 * Setter for <code>oa_salary.t_location.employee_unemployment</code>. 员工缴纳失业险比例 | 王默 | 2016-09-14 | 
	 */
	public void setEmployeeUnemployment(java.lang.Integer value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.employee_unemployment</code>. 员工缴纳失业险比例 | 王默 | 2016-09-14 | 
	 */
	public java.lang.Integer getEmployeeUnemployment() {
		return (java.lang.Integer) getValue(14);
	}

	/**
	 * Setter for <code>oa_salary.t_location.employee_housefund</code>. 员工缴纳住房公积金比例 | 王默 | 2016-09-14 | 
	 */
	public void setEmployeeHousefund(java.lang.Integer value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.employee_housefund</code>. 员工缴纳住房公积金比例 | 王默 | 2016-09-14 | 
	 */
	public java.lang.Integer getEmployeeHousefund() {
		return (java.lang.Integer) getValue(15);
	}

	/**
	 * Setter for <code>oa_salary.t_location.insurances_basefee_start</code>. 社保最低标准 | 王默 | 2016-09-14 | 
	 */
	public void setInsurancesBasefeeStart(java.lang.Integer value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.insurances_basefee_start</code>. 社保最低标准 | 王默 | 2016-09-14 | 
	 */
	public java.lang.Integer getInsurancesBasefeeStart() {
		return (java.lang.Integer) getValue(16);
	}

	/**
	 * Setter for <code>oa_salary.t_location.insurances_basefee_end</code>. 社保上限 | 王默 | 2016-09-14 | 
	 */
	public void setInsurancesBasefeeEnd(java.lang.Integer value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.insurances_basefee_end</code>. 社保上限 | 王默 | 2016-09-14 | 
	 */
	public java.lang.Integer getInsurancesBasefeeEnd() {
		return (java.lang.Integer) getValue(17);
	}

	/**
	 * Setter for <code>oa_salary.t_location.housefund_basefee_start</code>. 公积金最低标准 | 王默 | 2016-09-14 | 
	 */
	public void setHousefundBasefeeStart(java.lang.Integer value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.housefund_basefee_start</code>. 公积金最低标准 | 王默 | 2016-09-14 | 
	 */
	public java.lang.Integer getHousefundBasefeeStart() {
		return (java.lang.Integer) getValue(18);
	}

	/**
	 * Setter for <code>oa_salary.t_location.housefund_basefee_end</code>. 公积金上限 | 王默 | 2016-09-14 | 
	 */
	public void setHousefundBasefeeEnd(java.lang.Integer value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.housefund_basefee_end</code>. 公积金上限 | 王默 | 2016-09-14 | 
	 */
	public java.lang.Integer getHousefundBasefeeEnd() {
		return (java.lang.Integer) getValue(19);
	}

	/**
	 * Setter for <code>oa_salary.t_location.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(20);
	}

	/**
	 * Setter for <code>oa_salary.t_location.update_time</code>.
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.update_time</code>.
	 */
	public java.sql.Timestamp getUpdateTime() {
		return (java.sql.Timestamp) getValue(21);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record22 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row22<org.jooq.types.UInteger, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row22) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row22<org.jooq.types.UInteger, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row22) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return jooq.model.tables.TLocation.T_LOCATION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return jooq.model.tables.TLocation.T_LOCATION.PROVINCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return jooq.model.tables.TLocation.T_LOCATION.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return jooq.model.tables.TLocation.T_LOCATION.COUNTY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return jooq.model.tables.TLocation.T_LOCATION.COMPANY_ENDOWMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return jooq.model.tables.TLocation.T_LOCATION.COMPANY_MEDICAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return jooq.model.tables.TLocation.T_LOCATION.COMPANY_UNEMPLOYMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return jooq.model.tables.TLocation.T_LOCATION.COMPANY_MATERNITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return jooq.model.tables.TLocation.T_LOCATION.COMPANY_HOUSEFUND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return jooq.model.tables.TLocation.T_LOCATION.INDUSTRIAL_INJURY_START;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field11() {
		return jooq.model.tables.TLocation.T_LOCATION.INDUSTRIAL_JNJURY_END;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field12() {
		return jooq.model.tables.TLocation.T_LOCATION.INDUSTRIAL_INJURY_RECOMMENDED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field13() {
		return jooq.model.tables.TLocation.T_LOCATION.EMPLOYEE_ENDOWMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field14() {
		return jooq.model.tables.TLocation.T_LOCATION.EMPLOYEE_MEDICAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field15() {
		return jooq.model.tables.TLocation.T_LOCATION.EMPLOYEE_UNEMPLOYMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field16() {
		return jooq.model.tables.TLocation.T_LOCATION.EMPLOYEE_HOUSEFUND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field17() {
		return jooq.model.tables.TLocation.T_LOCATION.INSURANCES_BASEFEE_START;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field18() {
		return jooq.model.tables.TLocation.T_LOCATION.INSURANCES_BASEFEE_END;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field19() {
		return jooq.model.tables.TLocation.T_LOCATION.HOUSEFUND_BASEFEE_START;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field20() {
		return jooq.model.tables.TLocation.T_LOCATION.HOUSEFUND_BASEFEE_END;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field21() {
		return jooq.model.tables.TLocation.T_LOCATION.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field22() {
		return jooq.model.tables.TLocation.T_LOCATION.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getProvince();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getCounty();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getCompanyEndowment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getCompanyMedical();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getCompanyUnemployment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getCompanyMaternity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getCompanyHousefund();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getIndustrialInjuryStart();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value11() {
		return getIndustrialJnjuryEnd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value12() {
		return getIndustrialInjuryRecommended();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value13() {
		return getEmployeeEndowment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value14() {
		return getEmployeeMedical();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value15() {
		return getEmployeeUnemployment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value16() {
		return getEmployeeHousefund();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value17() {
		return getInsurancesBasefeeStart();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value18() {
		return getInsurancesBasefeeEnd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value19() {
		return getHousefundBasefeeStart();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value20() {
		return getHousefundBasefeeEnd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value21() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value22() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value1(org.jooq.types.UInteger value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value2(java.lang.String value) {
		setProvince(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value3(java.lang.String value) {
		setCity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value4(java.lang.String value) {
		setCounty(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value5(java.lang.Integer value) {
		setCompanyEndowment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value6(java.lang.Integer value) {
		setCompanyMedical(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value7(java.lang.Integer value) {
		setCompanyUnemployment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value8(java.lang.Integer value) {
		setCompanyMaternity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value9(java.lang.Integer value) {
		setCompanyHousefund(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value10(java.lang.Integer value) {
		setIndustrialInjuryStart(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value11(java.lang.Integer value) {
		setIndustrialJnjuryEnd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value12(java.lang.Integer value) {
		setIndustrialInjuryRecommended(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value13(java.lang.Integer value) {
		setEmployeeEndowment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value14(java.lang.Integer value) {
		setEmployeeMedical(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value15(java.lang.Integer value) {
		setEmployeeUnemployment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value16(java.lang.Integer value) {
		setEmployeeHousefund(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value17(java.lang.Integer value) {
		setInsurancesBasefeeStart(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value18(java.lang.Integer value) {
		setInsurancesBasefeeEnd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value19(java.lang.Integer value) {
		setHousefundBasefeeStart(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value20(java.lang.Integer value) {
		setHousefundBasefeeEnd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value21(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value22(java.sql.Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord values(org.jooq.types.UInteger value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.Integer value5, java.lang.Integer value6, java.lang.Integer value7, java.lang.Integer value8, java.lang.Integer value9, java.lang.Integer value10, java.lang.Integer value11, java.lang.Integer value12, java.lang.Integer value13, java.lang.Integer value14, java.lang.Integer value15, java.lang.Integer value16, java.lang.Integer value17, java.lang.Integer value18, java.lang.Integer value19, java.lang.Integer value20, java.sql.Timestamp value21, java.sql.Timestamp value22) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TLocationRecord
	 */
	public TLocationRecord() {
		super(jooq.model.tables.TLocation.T_LOCATION);
	}

	/**
	 * Create a detached, initialised TLocationRecord
	 */
	public TLocationRecord(org.jooq.types.UInteger id, java.lang.String province, java.lang.String city, java.lang.String county, java.lang.Integer companyEndowment, java.lang.Integer companyMedical, java.lang.Integer companyUnemployment, java.lang.Integer companyMaternity, java.lang.Integer companyHousefund, java.lang.Integer industrialInjuryStart, java.lang.Integer industrialJnjuryEnd, java.lang.Integer industrialInjuryRecommended, java.lang.Integer employeeEndowment, java.lang.Integer employeeMedical, java.lang.Integer employeeUnemployment, java.lang.Integer employeeHousefund, java.lang.Integer insurancesBasefeeStart, java.lang.Integer insurancesBasefeeEnd, java.lang.Integer housefundBasefeeStart, java.lang.Integer housefundBasefeeEnd, java.sql.Timestamp createTime, java.sql.Timestamp updateTime) {
		super(jooq.model.tables.TLocation.T_LOCATION);

		setValue(0, id);
		setValue(1, province);
		setValue(2, city);
		setValue(3, county);
		setValue(4, companyEndowment);
		setValue(5, companyMedical);
		setValue(6, companyUnemployment);
		setValue(7, companyMaternity);
		setValue(8, companyHousefund);
		setValue(9, industrialInjuryStart);
		setValue(10, industrialJnjuryEnd);
		setValue(11, industrialInjuryRecommended);
		setValue(12, employeeEndowment);
		setValue(13, employeeMedical);
		setValue(14, employeeUnemployment);
		setValue(15, employeeHousefund);
		setValue(16, insurancesBasefeeStart);
		setValue(17, insurancesBasefeeEnd);
		setValue(18, housefundBasefeeStart);
		setValue(19, housefundBasefeeEnd);
		setValue(20, createTime);
		setValue(21, updateTime);
	}
}
