/**
 * This class is generated by jOOQ
 */
package jooq.model.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * @depreciated 薪酬模块 | 记录位置和该位置社保公积金数据 | 邓刚&王默 | 2016-09-14 | 后台系统管理员输入  
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TLocationRecord extends org.jooq.impl.UpdatableRecordImpl<jooq.model.tables.records.TLocationRecord> implements org.jooq.Record13<org.jooq.types.UInteger, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 873452244;

	/**
	 * Setter for <code>oa_salary.t_location.id</code>.
	 */
	public void setId(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.id</code>.
	 */
	public org.jooq.types.UInteger getId() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>oa_salary.t_location.city</code>. 市级行政单位 | 邓刚&王默 | 2016-09-14 | 
	 */
	public void setCity(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.city</code>. 市级行政单位 | 邓刚&王默 | 2016-09-14 | 
	 */
	public java.lang.String getCity() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>oa_salary.t_location.cname</code>.
	 */
	public void setCname(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.cname</code>.
	 */
	public java.lang.String getCname() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>oa_salary.t_location.month</code>.
	 */
	public void setMonth(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.month</code>.
	 */
	public java.lang.String getMonth() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>oa_salary.t_location.pname</code>.
	 */
	public void setPname(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.pname</code>.
	 */
	public java.lang.String getPname() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>oa_salary.t_location.prov</code>. 省级行政单位  | 邓刚&王默 | 2016-09-14 | 
	 */
	public void setProv(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.prov</code>. 省级行政单位  | 邓刚&王默 | 2016-09-14 | 
	 */
	public java.lang.String getProv() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>oa_salary.t_location.region</code>. 县级行政单位 | 邓刚&王默 | 2016-09-14 | 
	 */
	public void setRegion(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.region</code>. 县级行政单位 | 邓刚&王默 | 2016-09-14 | 
	 */
	public java.lang.String getRegion() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>oa_salary.t_location.rule</code>.
	 */
	public void setRule(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.rule</code>.
	 */
	public java.lang.Integer getRule() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>oa_salary.t_location.subdl</code>.
	 */
	public void setSubdl(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.subdl</code>.
	 */
	public java.lang.Integer getSubdl() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>oa_salary.t_location.timestamp</code>.
	 */
	public void setTimestamp(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.timestamp</code>.
	 */
	public java.lang.String getTimestamp() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>oa_salary.t_location.last_date</code>.
	 */
	public void setLastDate(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.last_date</code>.
	 */
	public java.lang.String getLastDate() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>oa_salary.t_location.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(11);
	}

	/**
	 * Setter for <code>oa_salary.t_location.update_time</code>.
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>oa_salary.t_location.update_time</code>.
	 */
	public java.sql.Timestamp getUpdateTime() {
		return (java.sql.Timestamp) getValue(12);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record13 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row13<org.jooq.types.UInteger, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row13) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row13<org.jooq.types.UInteger, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row13) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return jooq.model.tables.TLocation.T_LOCATION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return jooq.model.tables.TLocation.T_LOCATION.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return jooq.model.tables.TLocation.T_LOCATION.CNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return jooq.model.tables.TLocation.T_LOCATION.MONTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return jooq.model.tables.TLocation.T_LOCATION.PNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return jooq.model.tables.TLocation.T_LOCATION.PROV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return jooq.model.tables.TLocation.T_LOCATION.REGION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return jooq.model.tables.TLocation.T_LOCATION.RULE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return jooq.model.tables.TLocation.T_LOCATION.SUBDL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return jooq.model.tables.TLocation.T_LOCATION.TIMESTAMP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return jooq.model.tables.TLocation.T_LOCATION.LAST_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field12() {
		return jooq.model.tables.TLocation.T_LOCATION.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field13() {
		return jooq.model.tables.TLocation.T_LOCATION.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getCname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getMonth();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getPname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getProv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getRegion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getRule();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getSubdl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getTimestamp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getLastDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value12() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value13() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value1(org.jooq.types.UInteger value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value2(java.lang.String value) {
		setCity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value3(java.lang.String value) {
		setCname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value4(java.lang.String value) {
		setMonth(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value5(java.lang.String value) {
		setPname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value6(java.lang.String value) {
		setProv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value7(java.lang.String value) {
		setRegion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value8(java.lang.Integer value) {
		setRule(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value9(java.lang.Integer value) {
		setSubdl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value10(java.lang.String value) {
		setTimestamp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value11(java.lang.String value) {
		setLastDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value12(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord value13(java.sql.Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TLocationRecord values(org.jooq.types.UInteger value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.Integer value8, java.lang.Integer value9, java.lang.String value10, java.lang.String value11, java.sql.Timestamp value12, java.sql.Timestamp value13) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TLocationRecord
	 */
	public TLocationRecord() {
		super(jooq.model.tables.TLocation.T_LOCATION);
	}

	/**
	 * Create a detached, initialised TLocationRecord
	 */
	public TLocationRecord(org.jooq.types.UInteger id, java.lang.String city, java.lang.String cname, java.lang.String month, java.lang.String pname, java.lang.String prov, java.lang.String region, java.lang.Integer rule, java.lang.Integer subdl, java.lang.String timestamp, java.lang.String lastDate, java.sql.Timestamp createTime, java.sql.Timestamp updateTime) {
		super(jooq.model.tables.TLocation.T_LOCATION);

		setValue(0, id);
		setValue(1, city);
		setValue(2, cname);
		setValue(3, month);
		setValue(4, pname);
		setValue(5, prov);
		setValue(6, region);
		setValue(7, rule);
		setValue(8, subdl);
		setValue(9, timestamp);
		setValue(10, lastDate);
		setValue(11, createTime);
		setValue(12, updateTime);
	}
}
