/**
 * This class is generated by jOOQ
 */
package jooq.model.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 计薪设置 | 邓刚&王默 | 2016-09-14 | 计薪设置页面，用户界面操作
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSalaryCalculationConfigRecord extends org.jooq.impl.UpdatableRecordImpl<jooq.model.tables.records.TSalaryCalculationConfigRecord> implements org.jooq.Record12<org.jooq.types.UInteger, java.lang.Long, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 776134666;

	/**
	 * Setter for <code>oa_salary.t_salary_calculation_config.id</code>.
	 */
	public void setId(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>oa_salary.t_salary_calculation_config.id</code>.
	 */
	public org.jooq.types.UInteger getId() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>oa_salary.t_salary_calculation_config.tenant_id</code>. 公司ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public void setTenantId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>oa_salary.t_salary_calculation_config.tenant_id</code>. 公司ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public java.lang.Long getTenantId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>oa_salary.t_salary_calculation_config.calculation_start</code>. 计薪开始是几号 | 邓刚&王默 | 2016-09-14 | 用户界面操作
	 */
	public void setCalculationStart(org.jooq.types.UByte value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>oa_salary.t_salary_calculation_config.calculation_start</code>. 计薪开始是几号 | 邓刚&王默 | 2016-09-14 | 用户界面操作
	 */
	public org.jooq.types.UByte getCalculationStart() {
		return (org.jooq.types.UByte) getValue(2);
	}

	/**
	 * Setter for <code>oa_salary.t_salary_calculation_config.calculation_end</code>. 计薪结束是几号 | 邓刚&王默 | 2016-09-14 | 用户界面操作
	 */
	public void setCalculationEnd(org.jooq.types.UByte value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>oa_salary.t_salary_calculation_config.calculation_end</code>. 计薪结束是几号 | 邓刚&王默 | 2016-09-14 | 用户界面操作
	 */
	public org.jooq.types.UByte getCalculationEnd() {
		return (org.jooq.types.UByte) getValue(3);
	}

	/**
	 * Setter for <code>oa_salary.t_salary_calculation_config.is_calculation_time_set</code>. 是不是已经设置过计薪开始日期，设置过之后不能更改 | 邓刚&王默 | 2016-09-14 | @1:未设置 @2:已设置 | 后台处理逻辑
	 */
	public void setIsCalculationTimeSet(org.jooq.types.UByte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>oa_salary.t_salary_calculation_config.is_calculation_time_set</code>. 是不是已经设置过计薪开始日期，设置过之后不能更改 | 邓刚&王默 | 2016-09-14 | @1:未设置 @2:已设置 | 后台处理逻辑
	 */
	public org.jooq.types.UByte getIsCalculationTimeSet() {
		return (org.jooq.types.UByte) getValue(4);
	}

	/**
	 * Setter for <code>oa_salary.t_salary_calculation_config.payoff_month</code>. 发薪月份 | 邓刚&王默 | 2016-09-14 | @0:本月发薪 @1:下月发薪 | 用户界面操作，选择
	 */
	public void setPayoffMonth(org.jooq.types.UByte value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>oa_salary.t_salary_calculation_config.payoff_month</code>. 发薪月份 | 邓刚&王默 | 2016-09-14 | @0:本月发薪 @1:下月发薪 | 用户界面操作，选择
	 */
	public org.jooq.types.UByte getPayoffMonth() {
		return (org.jooq.types.UByte) getValue(5);
	}

	/**
	 * Setter for <code>oa_salary.t_salary_calculation_config.payoff_day</code>. 发薪是几号 | 邓刚&王默 | 2016-09-14 | 用户界面操作，选择
	 */
	public void setPayoffDay(org.jooq.types.UByte value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>oa_salary.t_salary_calculation_config.payoff_day</code>. 发薪是几号 | 邓刚&王默 | 2016-09-14 | 用户界面操作，选择
	 */
	public org.jooq.types.UByte getPayoffDay() {
		return (org.jooq.types.UByte) getValue(6);
	}

	/**
	 * Setter for <code>oa_salary.t_salary_calculation_config.calculation_way</code>. 计薪方式 | 邓刚&王默 | 2016-09-14 | @1:11天为临界点 @2:21.75天为临界点 @3:按实际工作日计算 | 用户界面操作，选择
	 */
	public void setCalculationWay(org.jooq.types.UByte value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>oa_salary.t_salary_calculation_config.calculation_way</code>. 计薪方式 | 邓刚&王默 | 2016-09-14 | @1:11天为临界点 @2:21.75天为临界点 @3:按实际工作日计算 | 用户界面操作，选择
	 */
	public org.jooq.types.UByte getCalculationWay() {
		return (org.jooq.types.UByte) getValue(7);
	}

	/**
	 * Setter for <code>oa_salary.t_salary_calculation_config.insurances_data_source</code>. 社保数据源 | 邓刚&王默 | 2016-09-14 | @1:社保模块 @2:不计算社保 | 用户界面操作，选择
	 */
	public void setInsurancesDataSource(org.jooq.types.UByte value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>oa_salary.t_salary_calculation_config.insurances_data_source</code>. 社保数据源 | 邓刚&王默 | 2016-09-14 | @1:社保模块 @2:不计算社保 | 用户界面操作，选择
	 */
	public org.jooq.types.UByte getInsurancesDataSource() {
		return (org.jooq.types.UByte) getValue(8);
	}

	/**
	 * Setter for <code>oa_salary.t_salary_calculation_config.attendance_data_source</code>. 考勤数据源 | 邓刚&王默 | 2016-09-14 | @1:考勤模块 @2:自主上传 | 用户界面操作，选择 
	 */
	public void setAttendanceDataSource(org.jooq.types.UByte value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>oa_salary.t_salary_calculation_config.attendance_data_source</code>. 考勤数据源 | 邓刚&王默 | 2016-09-14 | @1:考勤模块 @2:自主上传 | 用户界面操作，选择 
	 */
	public org.jooq.types.UByte getAttendanceDataSource() {
		return (org.jooq.types.UByte) getValue(9);
	}

	/**
	 * Setter for <code>oa_salary.t_salary_calculation_config.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>oa_salary.t_salary_calculation_config.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>oa_salary.t_salary_calculation_config.update_time</code>.
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>oa_salary.t_salary_calculation_config.update_time</code>.
	 */
	public java.sql.Timestamp getUpdateTime() {
		return (java.sql.Timestamp) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<org.jooq.types.UInteger, java.lang.Long, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<org.jooq.types.UInteger, java.lang.Long, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return jooq.model.tables.TSalaryCalculationConfig.T_SALARY_CALCULATION_CONFIG.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return jooq.model.tables.TSalaryCalculationConfig.T_SALARY_CALCULATION_CONFIG.TENANT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field3() {
		return jooq.model.tables.TSalaryCalculationConfig.T_SALARY_CALCULATION_CONFIG.CALCULATION_START;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field4() {
		return jooq.model.tables.TSalaryCalculationConfig.T_SALARY_CALCULATION_CONFIG.CALCULATION_END;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field5() {
		return jooq.model.tables.TSalaryCalculationConfig.T_SALARY_CALCULATION_CONFIG.IS_CALCULATION_TIME_SET;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field6() {
		return jooq.model.tables.TSalaryCalculationConfig.T_SALARY_CALCULATION_CONFIG.PAYOFF_MONTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field7() {
		return jooq.model.tables.TSalaryCalculationConfig.T_SALARY_CALCULATION_CONFIG.PAYOFF_DAY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field8() {
		return jooq.model.tables.TSalaryCalculationConfig.T_SALARY_CALCULATION_CONFIG.CALCULATION_WAY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field9() {
		return jooq.model.tables.TSalaryCalculationConfig.T_SALARY_CALCULATION_CONFIG.INSURANCES_DATA_SOURCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field10() {
		return jooq.model.tables.TSalaryCalculationConfig.T_SALARY_CALCULATION_CONFIG.ATTENDANCE_DATA_SOURCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field11() {
		return jooq.model.tables.TSalaryCalculationConfig.T_SALARY_CALCULATION_CONFIG.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field12() {
		return jooq.model.tables.TSalaryCalculationConfig.T_SALARY_CALCULATION_CONFIG.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getTenantId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value3() {
		return getCalculationStart();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value4() {
		return getCalculationEnd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value5() {
		return getIsCalculationTimeSet();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value6() {
		return getPayoffMonth();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value7() {
		return getPayoffDay();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value8() {
		return getCalculationWay();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value9() {
		return getInsurancesDataSource();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value10() {
		return getAttendanceDataSource();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value11() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value12() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryCalculationConfigRecord value1(org.jooq.types.UInteger value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryCalculationConfigRecord value2(java.lang.Long value) {
		setTenantId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryCalculationConfigRecord value3(org.jooq.types.UByte value) {
		setCalculationStart(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryCalculationConfigRecord value4(org.jooq.types.UByte value) {
		setCalculationEnd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryCalculationConfigRecord value5(org.jooq.types.UByte value) {
		setIsCalculationTimeSet(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryCalculationConfigRecord value6(org.jooq.types.UByte value) {
		setPayoffMonth(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryCalculationConfigRecord value7(org.jooq.types.UByte value) {
		setPayoffDay(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryCalculationConfigRecord value8(org.jooq.types.UByte value) {
		setCalculationWay(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryCalculationConfigRecord value9(org.jooq.types.UByte value) {
		setInsurancesDataSource(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryCalculationConfigRecord value10(org.jooq.types.UByte value) {
		setAttendanceDataSource(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryCalculationConfigRecord value11(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryCalculationConfigRecord value12(java.sql.Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryCalculationConfigRecord values(org.jooq.types.UInteger value1, java.lang.Long value2, org.jooq.types.UByte value3, org.jooq.types.UByte value4, org.jooq.types.UByte value5, org.jooq.types.UByte value6, org.jooq.types.UByte value7, org.jooq.types.UByte value8, org.jooq.types.UByte value9, org.jooq.types.UByte value10, java.sql.Timestamp value11, java.sql.Timestamp value12) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TSalaryCalculationConfigRecord
	 */
	public TSalaryCalculationConfigRecord() {
		super(jooq.model.tables.TSalaryCalculationConfig.T_SALARY_CALCULATION_CONFIG);
	}

	/**
	 * Create a detached, initialised TSalaryCalculationConfigRecord
	 */
	public TSalaryCalculationConfigRecord(org.jooq.types.UInteger id, java.lang.Long tenantId, org.jooq.types.UByte calculationStart, org.jooq.types.UByte calculationEnd, org.jooq.types.UByte isCalculationTimeSet, org.jooq.types.UByte payoffMonth, org.jooq.types.UByte payoffDay, org.jooq.types.UByte calculationWay, org.jooq.types.UByte insurancesDataSource, org.jooq.types.UByte attendanceDataSource, java.sql.Timestamp createTime, java.sql.Timestamp updateTime) {
		super(jooq.model.tables.TSalaryCalculationConfig.T_SALARY_CALCULATION_CONFIG);

		setValue(0, id);
		setValue(1, tenantId);
		setValue(2, calculationStart);
		setValue(3, calculationEnd);
		setValue(4, isCalculationTimeSet);
		setValue(5, payoffMonth);
		setValue(6, payoffDay);
		setValue(7, calculationWay);
		setValue(8, insurancesDataSource);
		setValue(9, attendanceDataSource);
		setValue(10, createTime);
		setValue(11, updateTime);
	}
}
