/**
 * This class is generated by jOOQ
 */
package jooq.model.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 个人薪酬计算中一些动态变化的东西 | 邓刚&王默 | 2016-09-14 | 个人薪酬详情页面，用户界面操作
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSalaryConfigRecord extends org.jooq.impl.UpdatableRecordImpl<jooq.model.tables.records.TSalaryConfigRecord> implements org.jooq.Record8<org.jooq.types.ULong, java.lang.Long, java.lang.Long, java.lang.Double, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 1406876167;

	/**
	 * Setter for <code>oa_salary.t_salary_config.id</code>.
	 */
	public void setId(org.jooq.types.ULong value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>oa_salary.t_salary_config.id</code>.
	 */
	public org.jooq.types.ULong getId() {
		return (org.jooq.types.ULong) getValue(0);
	}

	/**
	 * Setter for <code>oa_salary.t_salary_config.tenant_id</code>. 公司ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public void setTenantId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>oa_salary.t_salary_config.tenant_id</code>. 公司ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public java.lang.Long getTenantId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>oa_salary.t_salary_config.user_id</code>. 用户ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public void setUserId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>oa_salary.t_salary_config.user_id</code>. 用户ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>oa_salary.t_salary_config.attendance_days</code>. 这个月出勤多少天 | 邓刚&王默 | 2016-09-14 | 输入？？？
	 */
	public void setAttendanceDays(java.lang.Double value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>oa_salary.t_salary_config.attendance_days</code>. 这个月出勤多少天 | 邓刚&王默 | 2016-09-14 | 输入？？？
	 */
	public java.lang.Double getAttendanceDays() {
		return (java.lang.Double) getValue(3);
	}

	/**
	 * Setter for <code>oa_salary.t_salary_config.before_tax_add_or_deduct</code>. 税前补扣款 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public void setBeforeTaxAddOrDeduct(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>oa_salary.t_salary_config.before_tax_add_or_deduct</code>. 税前补扣款 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public java.lang.Long getBeforeTaxAddOrDeduct() {
		return (java.lang.Long) getValue(4);
	}

	/**
	 * Setter for <code>oa_salary.t_salary_config.after_tax_add_or_deduct</code>. 税后补扣款 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public void setAfterTaxAddOrDeduct(java.lang.Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>oa_salary.t_salary_config.after_tax_add_or_deduct</code>. 税后补扣款 | 邓刚&王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public java.lang.Long getAfterTaxAddOrDeduct() {
		return (java.lang.Long) getValue(5);
	}

	/**
	 * Setter for <code>oa_salary.t_salary_config.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>oa_salary.t_salary_config.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>oa_salary.t_salary_config.update_time</code>.
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>oa_salary.t_salary_config.update_time</code>.
	 */
	public java.sql.Timestamp getUpdateTime() {
		return (java.sql.Timestamp) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.ULong> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<org.jooq.types.ULong, java.lang.Long, java.lang.Long, java.lang.Double, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<org.jooq.types.ULong, java.lang.Long, java.lang.Long, java.lang.Double, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.ULong> field1() {
		return jooq.model.tables.TSalaryConfig.T_SALARY_CONFIG.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return jooq.model.tables.TSalaryConfig.T_SALARY_CONFIG.TENANT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return jooq.model.tables.TSalaryConfig.T_SALARY_CONFIG.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field4() {
		return jooq.model.tables.TSalaryConfig.T_SALARY_CONFIG.ATTENDANCE_DAYS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return jooq.model.tables.TSalaryConfig.T_SALARY_CONFIG.BEFORE_TAX_ADD_OR_DEDUCT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field6() {
		return jooq.model.tables.TSalaryConfig.T_SALARY_CONFIG.AFTER_TAX_ADD_OR_DEDUCT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return jooq.model.tables.TSalaryConfig.T_SALARY_CONFIG.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return jooq.model.tables.TSalaryConfig.T_SALARY_CONFIG.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.ULong value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getTenantId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value4() {
		return getAttendanceDays();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getBeforeTaxAddOrDeduct();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value6() {
		return getAfterTaxAddOrDeduct();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryConfigRecord value1(org.jooq.types.ULong value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryConfigRecord value2(java.lang.Long value) {
		setTenantId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryConfigRecord value3(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryConfigRecord value4(java.lang.Double value) {
		setAttendanceDays(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryConfigRecord value5(java.lang.Long value) {
		setBeforeTaxAddOrDeduct(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryConfigRecord value6(java.lang.Long value) {
		setAfterTaxAddOrDeduct(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryConfigRecord value7(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryConfigRecord value8(java.sql.Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSalaryConfigRecord values(org.jooq.types.ULong value1, java.lang.Long value2, java.lang.Long value3, java.lang.Double value4, java.lang.Long value5, java.lang.Long value6, java.sql.Timestamp value7, java.sql.Timestamp value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TSalaryConfigRecord
	 */
	public TSalaryConfigRecord() {
		super(jooq.model.tables.TSalaryConfig.T_SALARY_CONFIG);
	}

	/**
	 * Create a detached, initialised TSalaryConfigRecord
	 */
	public TSalaryConfigRecord(org.jooq.types.ULong id, java.lang.Long tenantId, java.lang.Long userId, java.lang.Double attendanceDays, java.lang.Long beforeTaxAddOrDeduct, java.lang.Long afterTaxAddOrDeduct, java.sql.Timestamp createTime, java.sql.Timestamp updateTime) {
		super(jooq.model.tables.TSalaryConfig.T_SALARY_CONFIG);

		setValue(0, id);
		setValue(1, tenantId);
		setValue(2, userId);
		setValue(3, attendanceDays);
		setValue(4, beforeTaxAddOrDeduct);
		setValue(5, afterTaxAddOrDeduct);
		setValue(6, createTime);
		setValue(7, updateTime);
	}
}
