/**
 * This class is generated by jOOQ
 */
package jooq.model.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 社保补缴表 | 王默 | 2016-09-14 | 社保详情页面，用户界面操作
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSupplementaryInsurancesRecord extends org.jooq.impl.UpdatableRecordImpl<jooq.model.tables.records.TSupplementaryInsurancesRecord> implements org.jooq.Record15<org.jooq.types.ULong, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = -810616995;

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.id</code>.
	 */
	public void setId(org.jooq.types.ULong value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.id</code>.
	 */
	public org.jooq.types.ULong getId() {
		return (org.jooq.types.ULong) getValue(0);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.tenant_id</code>. 公司ID | 王默 | 2016-09-14 | 账号模块
	 */
	public void setTenantId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.tenant_id</code>. 公司ID | 王默 | 2016-09-14 | 账号模块
	 */
	public java.lang.Long getTenantId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.user_id</code>. 用户ID | 王默 | 2016-09-14 | 账号模块
	 */
	public void setUserId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.user_id</code>. 用户ID | 王默 | 2016-09-14 | 账号模块
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.current_month</code>. 当前时间 | 王默 | 2016-09-14 | 用户界面操作指示
	 */
	public void setCurrentMonth(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.current_month</code>. 当前时间 | 王默 | 2016-09-14 | 用户界面操作指示
	 */
	public java.lang.Integer getCurrentMonth() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.supplementary_pay_month</code>. 补缴的是哪一个月的 | 王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public void setSupplementaryPayMonth(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.supplementary_pay_month</code>. 补缴的是哪一个月的 | 王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public java.lang.Integer getSupplementaryPayMonth() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.company_endowment</code>. 公司养老保险补缴金额 | 王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public void setCompanyEndowment(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.company_endowment</code>. 公司养老保险补缴金额 | 王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public java.lang.Integer getCompanyEndowment() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.company_medical</code>. 公司医疗保险补缴金额 | 王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public void setCompanyMedical(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.company_medical</code>. 公司医疗保险补缴金额 | 王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public java.lang.Integer getCompanyMedical() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.company_unemployment</code>. 公司失业保险补缴金额 | 王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public void setCompanyUnemployment(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.company_unemployment</code>. 公司失业保险补缴金额 | 王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public java.lang.Integer getCompanyUnemployment() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.company_industrial_injury</code>. 公司工伤保险补缴金额 | 王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public void setCompanyIndustrialInjury(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.company_industrial_injury</code>. 公司工伤保险补缴金额 | 王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public java.lang.Integer getCompanyIndustrialInjury() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.company_maternity</code>. 公司生育保险补缴金额 | 王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public void setCompanyMaternity(java.lang.Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.company_maternity</code>. 公司生育保险补缴金额 | 王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public java.lang.Integer getCompanyMaternity() {
		return (java.lang.Integer) getValue(9);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.employee_endowment</code>. 个人养老保险补缴金额 | 王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public void setEmployeeEndowment(java.lang.Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.employee_endowment</code>. 个人养老保险补缴金额 | 王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public java.lang.Integer getEmployeeEndowment() {
		return (java.lang.Integer) getValue(10);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.employee_medical</code>. 个人医疗保险补缴金额 | 王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public void setEmployeeMedical(java.lang.Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.employee_medical</code>. 个人医疗保险补缴金额 | 王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public java.lang.Integer getEmployeeMedical() {
		return (java.lang.Integer) getValue(11);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.employee_unemployment</code>. 个人失业保险补缴金额 | 王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public void setEmployeeUnemployment(java.lang.Integer value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.employee_unemployment</code>. 个人失业保险补缴金额 | 王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public java.lang.Integer getEmployeeUnemployment() {
		return (java.lang.Integer) getValue(12);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(13);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.update_time</code>.
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.update_time</code>.
	 */
	public java.sql.Timestamp getUpdateTime() {
		return (java.sql.Timestamp) getValue(14);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.ULong> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record15 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row15<org.jooq.types.ULong, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row15) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row15<org.jooq.types.ULong, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row15) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.ULong> field1() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.TENANT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.CURRENT_MONTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.SUPPLEMENTARY_PAY_MONTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.COMPANY_ENDOWMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.COMPANY_MEDICAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.COMPANY_UNEMPLOYMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.COMPANY_INDUSTRIAL_INJURY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.COMPANY_MATERNITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field11() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.EMPLOYEE_ENDOWMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field12() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.EMPLOYEE_MEDICAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field13() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.EMPLOYEE_UNEMPLOYMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field14() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field15() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.ULong value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getTenantId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getCurrentMonth();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getSupplementaryPayMonth();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getCompanyEndowment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getCompanyMedical();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getCompanyUnemployment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getCompanyIndustrialInjury();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getCompanyMaternity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value11() {
		return getEmployeeEndowment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value12() {
		return getEmployeeMedical();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value13() {
		return getEmployeeUnemployment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value14() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value15() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value1(org.jooq.types.ULong value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value2(java.lang.Long value) {
		setTenantId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value3(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value4(java.lang.Integer value) {
		setCurrentMonth(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value5(java.lang.Integer value) {
		setSupplementaryPayMonth(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value6(java.lang.Integer value) {
		setCompanyEndowment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value7(java.lang.Integer value) {
		setCompanyMedical(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value8(java.lang.Integer value) {
		setCompanyUnemployment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value9(java.lang.Integer value) {
		setCompanyIndustrialInjury(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value10(java.lang.Integer value) {
		setCompanyMaternity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value11(java.lang.Integer value) {
		setEmployeeEndowment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value12(java.lang.Integer value) {
		setEmployeeMedical(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value13(java.lang.Integer value) {
		setEmployeeUnemployment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value14(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value15(java.sql.Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord values(org.jooq.types.ULong value1, java.lang.Long value2, java.lang.Long value3, java.lang.Integer value4, java.lang.Integer value5, java.lang.Integer value6, java.lang.Integer value7, java.lang.Integer value8, java.lang.Integer value9, java.lang.Integer value10, java.lang.Integer value11, java.lang.Integer value12, java.lang.Integer value13, java.sql.Timestamp value14, java.sql.Timestamp value15) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TSupplementaryInsurancesRecord
	 */
	public TSupplementaryInsurancesRecord() {
		super(jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES);
	}

	/**
	 * Create a detached, initialised TSupplementaryInsurancesRecord
	 */
	public TSupplementaryInsurancesRecord(org.jooq.types.ULong id, java.lang.Long tenantId, java.lang.Long userId, java.lang.Integer currentMonth, java.lang.Integer supplementaryPayMonth, java.lang.Integer companyEndowment, java.lang.Integer companyMedical, java.lang.Integer companyUnemployment, java.lang.Integer companyIndustrialInjury, java.lang.Integer companyMaternity, java.lang.Integer employeeEndowment, java.lang.Integer employeeMedical, java.lang.Integer employeeUnemployment, java.sql.Timestamp createTime, java.sql.Timestamp updateTime) {
		super(jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES);

		setValue(0, id);
		setValue(1, tenantId);
		setValue(2, userId);
		setValue(3, currentMonth);
		setValue(4, supplementaryPayMonth);
		setValue(5, companyEndowment);
		setValue(6, companyMedical);
		setValue(7, companyUnemployment);
		setValue(8, companyIndustrialInjury);
		setValue(9, companyMaternity);
		setValue(10, employeeEndowment);
		setValue(11, employeeMedical);
		setValue(12, employeeUnemployment);
		setValue(13, createTime);
		setValue(14, updateTime);
	}
}
