/**
 * This class is generated by jOOQ
 */
package jooq.model.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 社保补缴表 | 邓刚&王默 | 2016-09-14 | 社保详情页面，用户界面操作
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSupplementaryInsurancesRecord extends org.jooq.impl.UpdatableRecordImpl<jooq.model.tables.records.TSupplementaryInsurancesRecord> implements org.jooq.Record21<org.jooq.types.ULong, java.lang.Long, java.lang.Long, java.lang.Byte, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 2045277412;

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.id</code>.
	 */
	public void setId(org.jooq.types.ULong value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.id</code>.
	 */
	public org.jooq.types.ULong getId() {
		return (org.jooq.types.ULong) getValue(0);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.tenant_id</code>. 公司ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public void setTenantId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.tenant_id</code>. 公司ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public java.lang.Long getTenantId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.user_id</code>. 用户ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public void setUserId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.user_id</code>. 用户ID | 邓刚&王默 | 2016-09-14 | 账号模块
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.is_enabled</code>. 是否启用 | 邓刚&王默 | 2016-10-18 | @1：启用 @2：停用
	 */
	public void setIsEnabled(java.lang.Byte value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.is_enabled</code>. 是否启用 | 邓刚&王默 | 2016-10-18 | @1：启用 @2：停用
	 */
	public java.lang.Byte getIsEnabled() {
		return (java.lang.Byte) getValue(3);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.company_total</code>.
	 */
	public void setCompanyTotal(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.company_total</code>.
	 */
	public java.lang.Long getCompanyTotal() {
		return (java.lang.Long) getValue(4);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.company_endowment</code>. 公司养老保险补缴金额 | 邓刚&王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public void setCompanyEndowment(java.lang.Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.company_endowment</code>. 公司养老保险补缴金额 | 邓刚&王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public java.lang.Long getCompanyEndowment() {
		return (java.lang.Long) getValue(5);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.company_medical</code>. 公司医疗保险补缴金额 | 邓刚&王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public void setCompanyMedical(java.lang.Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.company_medical</code>. 公司医疗保险补缴金额 | 邓刚&王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public java.lang.Long getCompanyMedical() {
		return (java.lang.Long) getValue(6);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.company_unemployment</code>. 公司失业保险补缴金额 | 邓刚&王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public void setCompanyUnemployment(java.lang.Long value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.company_unemployment</code>. 公司失业保险补缴金额 | 邓刚&王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public java.lang.Long getCompanyUnemployment() {
		return (java.lang.Long) getValue(7);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.company_industrial_injury</code>. 公司工伤保险补缴金额 | 邓刚&王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public void setCompanyIndustrialInjury(java.lang.Long value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.company_industrial_injury</code>. 公司工伤保险补缴金额 | 邓刚&王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public java.lang.Long getCompanyIndustrialInjury() {
		return (java.lang.Long) getValue(8);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.company_maternity</code>. 公司生育保险补缴金额 | 邓刚&王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public void setCompanyMaternity(java.lang.Long value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.company_maternity</code>. 公司生育保险补缴金额 | 邓刚&王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public java.lang.Long getCompanyMaternity() {
		return (java.lang.Long) getValue(9);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.employee_total</code>.
	 */
	public void setEmployeeTotal(java.lang.Long value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.employee_total</code>.
	 */
	public java.lang.Long getEmployeeTotal() {
		return (java.lang.Long) getValue(10);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.employee_endowment</code>. 个人养老保险补缴金额 | 邓刚&王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public void setEmployeeEndowment(java.lang.Long value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.employee_endowment</code>. 个人养老保险补缴金额 | 邓刚&王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public java.lang.Long getEmployeeEndowment() {
		return (java.lang.Long) getValue(11);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.employee_medical</code>. 个人医疗保险补缴金额 | 邓刚&王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public void setEmployeeMedical(java.lang.Long value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.employee_medical</code>. 个人医疗保险补缴金额 | 邓刚&王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public java.lang.Long getEmployeeMedical() {
		return (java.lang.Long) getValue(12);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.employee_unemployment</code>. 个人失业保险补缴金额 | 邓刚&王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public void setEmployeeUnemployment(java.lang.Long value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.employee_unemployment</code>. 个人失业保险补缴金额 | 邓刚&王默 | 2016-09-14 | 根据本月基数和location生成
	 */
	public java.lang.Long getEmployeeUnemployment() {
		return (java.lang.Long) getValue(13);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.employee_industrial_injury</code>.
	 */
	public void setEmployeeIndustrialInjury(java.lang.Long value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.employee_industrial_injury</code>.
	 */
	public java.lang.Long getEmployeeIndustrialInjury() {
		return (java.lang.Long) getValue(14);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.employee_maternity</code>.
	 */
	public void setEmployeeMaternity(java.lang.Long value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.employee_maternity</code>.
	 */
	public java.lang.Long getEmployeeMaternity() {
		return (java.lang.Long) getValue(15);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.company_ill_fee</code>. 大病医疗
	 */
	public void setCompanyIllFee(java.lang.Long value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.company_ill_fee</code>. 大病医疗
	 */
	public java.lang.Long getCompanyIllFee() {
		return (java.lang.Long) getValue(16);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.employee_ill_fee</code>.
	 */
	public void setEmployeeIllFee(java.lang.Long value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.employee_ill_fee</code>.
	 */
	public java.lang.Long getEmployeeIllFee() {
		return (java.lang.Long) getValue(17);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.describ</code>.
	 */
	public void setDescrib(java.lang.String value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.describ</code>.
	 */
	public java.lang.String getDescrib() {
		return (java.lang.String) getValue(18);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(19);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_insurances.update_time</code>.
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_insurances.update_time</code>.
	 */
	public java.sql.Timestamp getUpdateTime() {
		return (java.sql.Timestamp) getValue(20);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.ULong> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record21 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row21<org.jooq.types.ULong, java.lang.Long, java.lang.Long, java.lang.Byte, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row21) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row21<org.jooq.types.ULong, java.lang.Long, java.lang.Long, java.lang.Byte, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row21) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.ULong> field1() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.TENANT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field4() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.IS_ENABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.COMPANY_TOTAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field6() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.COMPANY_ENDOWMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field7() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.COMPANY_MEDICAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field8() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.COMPANY_UNEMPLOYMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field9() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.COMPANY_INDUSTRIAL_INJURY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field10() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.COMPANY_MATERNITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field11() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.EMPLOYEE_TOTAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field12() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.EMPLOYEE_ENDOWMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field13() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.EMPLOYEE_MEDICAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field14() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.EMPLOYEE_UNEMPLOYMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field15() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.EMPLOYEE_INDUSTRIAL_INJURY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field16() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.EMPLOYEE_MATERNITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field17() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.COMPANY_ILL_FEE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field18() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.EMPLOYEE_ILL_FEE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field19() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.DESCRIB;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field20() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field21() {
		return jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.ULong value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getTenantId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value4() {
		return getIsEnabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getCompanyTotal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value6() {
		return getCompanyEndowment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value7() {
		return getCompanyMedical();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value8() {
		return getCompanyUnemployment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value9() {
		return getCompanyIndustrialInjury();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value10() {
		return getCompanyMaternity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value11() {
		return getEmployeeTotal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value12() {
		return getEmployeeEndowment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value13() {
		return getEmployeeMedical();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value14() {
		return getEmployeeUnemployment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value15() {
		return getEmployeeIndustrialInjury();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value16() {
		return getEmployeeMaternity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value17() {
		return getCompanyIllFee();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value18() {
		return getEmployeeIllFee();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value19() {
		return getDescrib();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value20() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value21() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value1(org.jooq.types.ULong value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value2(java.lang.Long value) {
		setTenantId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value3(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value4(java.lang.Byte value) {
		setIsEnabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value5(java.lang.Long value) {
		setCompanyTotal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value6(java.lang.Long value) {
		setCompanyEndowment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value7(java.lang.Long value) {
		setCompanyMedical(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value8(java.lang.Long value) {
		setCompanyUnemployment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value9(java.lang.Long value) {
		setCompanyIndustrialInjury(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value10(java.lang.Long value) {
		setCompanyMaternity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value11(java.lang.Long value) {
		setEmployeeTotal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value12(java.lang.Long value) {
		setEmployeeEndowment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value13(java.lang.Long value) {
		setEmployeeMedical(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value14(java.lang.Long value) {
		setEmployeeUnemployment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value15(java.lang.Long value) {
		setEmployeeIndustrialInjury(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value16(java.lang.Long value) {
		setEmployeeMaternity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value17(java.lang.Long value) {
		setCompanyIllFee(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value18(java.lang.Long value) {
		setEmployeeIllFee(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value19(java.lang.String value) {
		setDescrib(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value20(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord value21(java.sql.Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryInsurancesRecord values(org.jooq.types.ULong value1, java.lang.Long value2, java.lang.Long value3, java.lang.Byte value4, java.lang.Long value5, java.lang.Long value6, java.lang.Long value7, java.lang.Long value8, java.lang.Long value9, java.lang.Long value10, java.lang.Long value11, java.lang.Long value12, java.lang.Long value13, java.lang.Long value14, java.lang.Long value15, java.lang.Long value16, java.lang.Long value17, java.lang.Long value18, java.lang.String value19, java.sql.Timestamp value20, java.sql.Timestamp value21) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TSupplementaryInsurancesRecord
	 */
	public TSupplementaryInsurancesRecord() {
		super(jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES);
	}

	/**
	 * Create a detached, initialised TSupplementaryInsurancesRecord
	 */
	public TSupplementaryInsurancesRecord(org.jooq.types.ULong id, java.lang.Long tenantId, java.lang.Long userId, java.lang.Byte isEnabled, java.lang.Long companyTotal, java.lang.Long companyEndowment, java.lang.Long companyMedical, java.lang.Long companyUnemployment, java.lang.Long companyIndustrialInjury, java.lang.Long companyMaternity, java.lang.Long employeeTotal, java.lang.Long employeeEndowment, java.lang.Long employeeMedical, java.lang.Long employeeUnemployment, java.lang.Long employeeIndustrialInjury, java.lang.Long employeeMaternity, java.lang.Long companyIllFee, java.lang.Long employeeIllFee, java.lang.String describ, java.sql.Timestamp createTime, java.sql.Timestamp updateTime) {
		super(jooq.model.tables.TSupplementaryInsurances.T_SUPPLEMENTARY_INSURANCES);

		setValue(0, id);
		setValue(1, tenantId);
		setValue(2, userId);
		setValue(3, isEnabled);
		setValue(4, companyTotal);
		setValue(5, companyEndowment);
		setValue(6, companyMedical);
		setValue(7, companyUnemployment);
		setValue(8, companyIndustrialInjury);
		setValue(9, companyMaternity);
		setValue(10, employeeTotal);
		setValue(11, employeeEndowment);
		setValue(12, employeeMedical);
		setValue(13, employeeUnemployment);
		setValue(14, employeeIndustrialInjury);
		setValue(15, employeeMaternity);
		setValue(16, companyIllFee);
		setValue(17, employeeIllFee);
		setValue(18, describ);
		setValue(19, createTime);
		setValue(20, updateTime);
	}
}
