/**
 * This class is generated by jOOQ
 */
package jooq.model.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 薪酬模块 | 公积金补缴表 | 王默 | 2016-09-14 | 社保详情页面，用户界面操作
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSupplementaryHousefundRecord extends org.jooq.impl.UpdatableRecordImpl<jooq.model.tables.records.TSupplementaryHousefundRecord> implements org.jooq.Record9<org.jooq.types.ULong, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 1725050212;

	/**
	 * Setter for <code>oa_salary.t_supplementary_housefund.id</code>.
	 */
	public void setId(org.jooq.types.ULong value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_housefund.id</code>.
	 */
	public org.jooq.types.ULong getId() {
		return (org.jooq.types.ULong) getValue(0);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_housefund.tenant_id</code>. 公司ID | 王默 | 2016-09-14 | 账号模块
	 */
	public void setTenantId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_housefund.tenant_id</code>. 公司ID | 王默 | 2016-09-14 | 账号模块
	 */
	public java.lang.Long getTenantId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_housefund.user_id</code>. 用户ID | 王默 | 2016-09-14 | 账号模块
	 */
	public void setUserId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_housefund.user_id</code>. 用户ID | 王默 | 2016-09-14 | 账号模块
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_housefund.current_month</code>. 当前时间 | 王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public void setCurrentMonth(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_housefund.current_month</code>. 当前时间 | 王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public java.lang.Integer getCurrentMonth() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_housefund.supplementary_pay_month</code>. 补缴的是哪一个月的 | 王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public void setSupplementaryPayMonth(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_housefund.supplementary_pay_month</code>. 补缴的是哪一个月的 | 王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public java.lang.Integer getSupplementaryPayMonth() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_housefund.company_housefund</code>. 公司公积金补缴金额 | 王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public void setCompanyHousefund(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_housefund.company_housefund</code>. 公司公积金补缴金额 | 王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public java.lang.Integer getCompanyHousefund() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_housefund.employee_housefund</code>. 个人公积金补缴金额 | 王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public void setEmployeeHousefund(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_housefund.employee_housefund</code>. 个人公积金补缴金额 | 王默 | 2016-09-14 | 用户界面操作，输入
	 */
	public java.lang.Integer getEmployeeHousefund() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_housefund.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_housefund.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>oa_salary.t_supplementary_housefund.update_time</code>.
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>oa_salary.t_supplementary_housefund.update_time</code>.
	 */
	public java.sql.Timestamp getUpdateTime() {
		return (java.sql.Timestamp) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.ULong> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<org.jooq.types.ULong, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<org.jooq.types.ULong, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.ULong> field1() {
		return jooq.model.tables.TSupplementaryHousefund.T_SUPPLEMENTARY_HOUSEFUND.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return jooq.model.tables.TSupplementaryHousefund.T_SUPPLEMENTARY_HOUSEFUND.TENANT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return jooq.model.tables.TSupplementaryHousefund.T_SUPPLEMENTARY_HOUSEFUND.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return jooq.model.tables.TSupplementaryHousefund.T_SUPPLEMENTARY_HOUSEFUND.CURRENT_MONTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return jooq.model.tables.TSupplementaryHousefund.T_SUPPLEMENTARY_HOUSEFUND.SUPPLEMENTARY_PAY_MONTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return jooq.model.tables.TSupplementaryHousefund.T_SUPPLEMENTARY_HOUSEFUND.COMPANY_HOUSEFUND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return jooq.model.tables.TSupplementaryHousefund.T_SUPPLEMENTARY_HOUSEFUND.EMPLOYEE_HOUSEFUND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return jooq.model.tables.TSupplementaryHousefund.T_SUPPLEMENTARY_HOUSEFUND.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field9() {
		return jooq.model.tables.TSupplementaryHousefund.T_SUPPLEMENTARY_HOUSEFUND.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.ULong value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getTenantId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getCurrentMonth();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getSupplementaryPayMonth();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getCompanyHousefund();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getEmployeeHousefund();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value9() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryHousefundRecord value1(org.jooq.types.ULong value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryHousefundRecord value2(java.lang.Long value) {
		setTenantId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryHousefundRecord value3(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryHousefundRecord value4(java.lang.Integer value) {
		setCurrentMonth(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryHousefundRecord value5(java.lang.Integer value) {
		setSupplementaryPayMonth(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryHousefundRecord value6(java.lang.Integer value) {
		setCompanyHousefund(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryHousefundRecord value7(java.lang.Integer value) {
		setEmployeeHousefund(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryHousefundRecord value8(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryHousefundRecord value9(java.sql.Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TSupplementaryHousefundRecord values(org.jooq.types.ULong value1, java.lang.Long value2, java.lang.Long value3, java.lang.Integer value4, java.lang.Integer value5, java.lang.Integer value6, java.lang.Integer value7, java.sql.Timestamp value8, java.sql.Timestamp value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TSupplementaryHousefundRecord
	 */
	public TSupplementaryHousefundRecord() {
		super(jooq.model.tables.TSupplementaryHousefund.T_SUPPLEMENTARY_HOUSEFUND);
	}

	/**
	 * Create a detached, initialised TSupplementaryHousefundRecord
	 */
	public TSupplementaryHousefundRecord(org.jooq.types.ULong id, java.lang.Long tenantId, java.lang.Long userId, java.lang.Integer currentMonth, java.lang.Integer supplementaryPayMonth, java.lang.Integer companyHousefund, java.lang.Integer employeeHousefund, java.sql.Timestamp createTime, java.sql.Timestamp updateTime) {
		super(jooq.model.tables.TSupplementaryHousefund.T_SUPPLEMENTARY_HOUSEFUND);

		setValue(0, id);
		setValue(1, tenantId);
		setValue(2, userId);
		setValue(3, currentMonth);
		setValue(4, supplementaryPayMonth);
		setValue(5, companyHousefund);
		setValue(6, employeeHousefund);
		setValue(7, createTime);
		setValue(8, updateTime);
	}
}
