package mybatis.mapper;

import java.util.List;
import mybatis.dao.model.HouseFundPlan;
import mybatis.dao.model.HouseFundPlanExample;
import org.apache.ibatis.annotations.Param;

public interface HouseFundPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_housefund_plan
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    int countByExample(HouseFundPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_housefund_plan
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    int deleteByExample(HouseFundPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_housefund_plan
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_housefund_plan
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    int insert(HouseFundPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_housefund_plan
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    int insertSelective(HouseFundPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_housefund_plan
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    List<HouseFundPlan> selectByExample(HouseFundPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_housefund_plan
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    HouseFundPlan selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_housefund_plan
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") HouseFundPlan record, @Param("example") HouseFundPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_housefund_plan
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    int updateByExample(@Param("record") HouseFundPlan record, @Param("example") HouseFundPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_housefund_plan
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    int updateByPrimaryKeySelective(HouseFundPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_housefund_plan
     *
     * @mbggenerated Thu Dec 29 14:14:58 CST 2016
     */
    int updateByPrimaryKey(HouseFundPlan record);
}